package mctmods.basemod.items.meta;

import net.minecraft.item.EnumRarity;
import net.minecraft.util.IStringSerializable;

public enum EnumMaterials implements IStringSerializable {

	OPEN_0000	  ("open"		   , EnumRarity.COMMON, ""			 , ""	   , 64),
	OPEN_0001	  ("open"		   , EnumRarity.COMMON, ""			 , ""	   , 64),
	IRON_DUST_DIRTY("iron_dust_dirty", EnumRarity.COMMON, "dustDirtyIron", ""	   , 64),
	OPEN_0002	  ("open"		   , EnumRarity.COMMON, ""			 , ""	   , 64),
	IRON_SHARD	 ("iron_shard"	 , EnumRarity.COMMON, "shardIron"	, ""	   , 64),
	OPEN_0003	  ("open"		   , EnumRarity.COMMON, ""			 , ""	   , 64),
	IRON_CLUMP	 ("iron_clump"	 , EnumRarity.COMMON, "clumpIron"	, ""	   , 64),
	OPEN_0004	  ("open"		   , EnumRarity.COMMON, ""			 , ""	   , 64),
	IRON_ROD	   ("iron_rod"	   , EnumRarity.COMMON, "stickIron"	, "rodIron", 64),
	IRON_GEAR	  ("iron_gear"	  , EnumRarity.COMMON, "gearIron"	 , ""	   , 64),
	IRON_PLATE	 ("iron_plate"	 , EnumRarity.COMMON, "plateIron"	, ""	   , 64),

	OPEN_0005	  ("open"		   , EnumRarity.COMMON, ""			 , ""	   , 64),
	OPEN_0006	  ("open"		   , EnumRarity.COMMON, ""			 , ""	   , 64),
	GOLD_DUST_DIRTY("gold_dust_dirty", EnumRarity.COMMON, "dustDirtyGold", ""	   , 64),
	OPEN_0007	  ("open"		   , EnumRarity.COMMON, ""			 , ""	   , 64),
	GOLD_SHARD	 ("gold_shard"	 , EnumRarity.COMMON, "shardGold"	, ""	   , 64),
	OPEN_0008	  ("open"		   , EnumRarity.COMMON, ""			 , ""	   , 64),
	GOLD_CLUMP	 ("gold_clump"	 , EnumRarity.COMMON, "clumpGold"	, ""	   , 64),
	OPEN_0009	  ("open"		   , EnumRarity.COMMON, ""			 , ""	   , 64),
	GOLD_ROD	   ("gold_rod"	   , EnumRarity.COMMON, "stickGold"	, "rodGold", 64),
	GOLD_GEAR	  ("gold_gear"	  , EnumRarity.COMMON, "gearGold"	 , ""	   , 64),
	GOLD_PLATE	 ("gold_plate"	 , EnumRarity.COMMON, "plateGold"	, ""	   , 64),

	OPEN_0010		("open"			 , EnumRarity.COMMON, ""			   , ""		 , 64),
	OPEN_0011		("open"			 , EnumRarity.COMMON, ""			   , ""		 , 64),
	COPPER_DUST_DIRTY("copper_dust_dirty", EnumRarity.COMMON, "dustDirtyCopper", ""		 , 64),
	OPEN_0012		("open"			 , EnumRarity.COMMON, ""			   , ""		 , 64),
	COPPER_SHARD	 ("copper_shard"	 , EnumRarity.COMMON, "shardCopper"	, ""		 , 64),
	COPPER_NUGGET	("copper_nugget"	, EnumRarity.COMMON, "nuggetCopper"   , ""		 , 64),
	COPPER_CLUMP	 ("copper_clump"	 , EnumRarity.COMMON, "clumpCopper"	, ""		 , 64),
	COPPER_INGOT	 ("copper_ingot"	 , EnumRarity.COMMON, "ingotCopper"	, ""		 , 64),
	COPPER_ROD	   ("copper_rod"	   , EnumRarity.COMMON, "stickCopper"	, "rodCopper", 64),
	COPPER_GEAR	  ("copper_gear"	  , EnumRarity.COMMON, "gearCopper"	 , ""		 , 64),
	COPPER_PLATE	 ("copper_plate"	 , EnumRarity.COMMON, "plateCopper"	, ""		 , 64),

	OPEN_0013	 ("open"		  , EnumRarity.COMMON, ""			, ""	  , 64),
	OPEN_0014	 ("open"		  , EnumRarity.COMMON, ""			, ""	  , 64),
	TIN_DUST_DIRTY("tin_dust_dirty", EnumRarity.COMMON, "dustDirtyTin", ""	  , 64),
	OPEN_0015	 ("open"		  , EnumRarity.COMMON, ""			, ""	  , 64),
	TIN_SHARD	 ("tin_shard"	 , EnumRarity.COMMON, "shardTin"	, ""	  , 64),
	TIN_NUGGET	("tin_nugget"	, EnumRarity.COMMON, "nuggetTin"   , ""	  , 64),
	TIN_CLUMP	 ("tin_clump"	 , EnumRarity.COMMON, "clumpTin"	, ""	  , 64),
	TIN_INGOT	 ("tin_ingot"	 , EnumRarity.COMMON, "ingotTin"	, ""	  , 64),
	TIN_ROD	   ("tin_rod"	   , EnumRarity.COMMON, "stickTin"	, "rodTin", 64),
	TIN_GEAR	  ("tin_gear"	  , EnumRarity.COMMON, "gearTin"	 , ""	  , 64),
	TIN_PLATE	 ("tin_plate"	 , EnumRarity.COMMON, "plateTin"	, ""	  , 64),

	OPEN_0016		("open"			 , EnumRarity.COMMON, ""			   , ""		 , 64),
	OPEN_0017		("open"			 , EnumRarity.COMMON, ""			   , ""		 , 64),
	NICKEL_DUST_DIRTY("nickel_dust_dirty", EnumRarity.COMMON, "dustDirtyNickel", ""		 , 64),
	OPEN_0018		("open"			 , EnumRarity.COMMON, ""			   , ""		 , 64),
	NICKEL_SHARD	 ("nickel_shard"	 , EnumRarity.COMMON, "shardNickel"	, ""		 , 64),
	NICKEL_NUGGET	("nickel_nugget"	, EnumRarity.COMMON, "nuggetNickel"   , ""		 , 64),
	NICKEL_CLUMP	 ("nickel_clump"	 , EnumRarity.COMMON, "clumpNickel"	, ""		 , 64),
	NICKEL_INGOT	 ("nickel_ingot"	 , EnumRarity.COMMON, "ingotNickel"	, ""		 , 64),
	NICKEL_ROD	   ("nickel_rod"	   , EnumRarity.COMMON, "stickNickel"	, "rodNickel", 64),
	NICKEL_GEAR	  ("nickel_gear"	  , EnumRarity.COMMON, "gearNickel"	 , ""		 , 64),
	NICKEL_PLATE	 ("nickel_plate"	 , EnumRarity.COMMON, "plateNickel"	, ""		 , 64),

	OPEN_0019		("open"			 , EnumRarity.COMMON  , ""			   , ""		 , 64),
	OPEN_0020		("open"			 , EnumRarity.COMMON  , ""			   , ""		 , 64),
	SILVER_DUST_DIRTY("silver_dust_dirty", EnumRarity.UNCOMMON, "dustDirtySilver", ""		 , 64),
	OPEN_0021		("open"			 , EnumRarity.COMMON  , ""			   , ""		 , 64),
	SILVER_SHARD	 ("silver_shard"	 , EnumRarity.UNCOMMON, "shardSilver"	, ""		 , 64),
	SILVER_NUGGET	("silver_nugget"	, EnumRarity.UNCOMMON, "nuggetSilver"   , ""		 , 64),
	SILVER_CLUMP	 ("silver_clump"	 , EnumRarity.UNCOMMON, "clumpSilver"	, ""		 , 64),
	SILVER_INGOT	 ("silver_ingot"	 , EnumRarity.UNCOMMON, "ingotSilver"	, ""		 , 64),
	SILVER_ROD	   ("silver_rod"	   , EnumRarity.UNCOMMON, "stickSilver"	, "rodSilver", 64),
	SILVER_GEAR	  ("silver_gear"	  , EnumRarity.UNCOMMON, "gearSilver"	 , ""		 , 64),
	SILVER_PLATE	 ("silver_plate"	 , EnumRarity.UNCOMMON, "plateSilver"	, ""		 , 64),

	OPEN_0022	  ("open"		   , EnumRarity.COMMON  , ""			 , ""	   , 64),
	OPEN_0023	  ("open"		   , EnumRarity.COMMON  , ""			 , ""	   , 64),
	LEAD_DUST_DIRTY("lead_dust_dirty", EnumRarity.UNCOMMON, "dustDirtyLead", ""	   , 64),
	OPEN_0024	  ("open"		   , EnumRarity.COMMON  , ""			 , ""	   , 64),
	LEAD_SHARD	 ("lead_shard"	 , EnumRarity.UNCOMMON, "shardLead"	, ""	   , 64),
	LEAD_NUGGET	("lead_nugget"	, EnumRarity.UNCOMMON, "nuggetLead"   , ""	   , 64),
	LEAD_CLUMP	 ("lead_clump"	 , EnumRarity.UNCOMMON, "clumpLead"	, ""	   , 64),
	LEAD_INGOT	 ("lead_ingot"	 , EnumRarity.UNCOMMON, "ingotLead"	, ""	   , 64),
	LEAD_ROD	   ("lead_rod"	   , EnumRarity.UNCOMMON, "stickLead"	, "rodLead", 64),
	LEAD_GEAR	  ("lead_gear"	  , EnumRarity.UNCOMMON, "gearLead"	 , ""	   , 64),
	LEAD_PLATE	 ("lead_plate"	 , EnumRarity.UNCOMMON, "plateLead"	, ""	   , 64),

	OPEN_0025		  ("open"				, EnumRarity.COMMON , ""				 , ""		   , 64),
	OPEN_0026		  ("open"				, EnumRarity.COMMON , ""				 , ""		   , 64),
	ALUMINUM_DUST_DIRTY("aluminum_dust_dirty", EnumRarity.UNCOMMON, "dustDirtyAluminum", ""		   , 64),
	OPEN_0027		  ("open"			   , EnumRarity.COMMON  , ""				 , ""		   , 64),
	ALUMINUM_SHARD	 ("aluminum_shard"	 , EnumRarity.UNCOMMON, "shardAluminum"	, ""		   , 64),
	ALUMINUM_NUGGET	("aluminum_nugget"	, EnumRarity.UNCOMMON, "nuggetAluminum"   , ""		   , 64),
	ALUMINUM_CLUMP	 ("aluminum_clump"	 , EnumRarity.UNCOMMON, "clumpAluminum"	, ""		   , 64),
	ALUMINUM_INGOT	 ("aluminum_ingot"	 , EnumRarity.UNCOMMON, "ingotAluminum"	, ""		   , 64),
	ALUMINUM_ROD	   ("aluminum_rod"	   , EnumRarity.UNCOMMON, "stickAluminum"	, "rodAluminum", 64),
	ALUMINUM_GEAR	  ("aluminum_gear"	  , EnumRarity.UNCOMMON, "gearAluminum"	 , ""		   , 64),
	ALUMINUM_PLATE	 ("aluminum_plate"	 , EnumRarity.UNCOMMON, "plateAluminum"	, ""		   , 64),

	OPEN_0028		("open"			 , EnumRarity.COMMON  , ""			   , ""		 , 64),
	OPEN_0029		("open"			 , EnumRarity.COMMON  , ""			   , ""		 , 64),
	OSMIUM_DUST_DIRTY("osmium_dust_dirty", EnumRarity.UNCOMMON, "dustDirtyOsmium", ""		 , 64),
	OPEN_0030		("open"			 , EnumRarity.COMMON  , ""			   , ""		 , 64),
	OSMIUM_SHARD	 ("osmium_shard"	 , EnumRarity.UNCOMMON, "shardOsmium"	, ""		 , 64),
	OSMIUM_NUGGET	("osmium_nugget"	, EnumRarity.UNCOMMON, "nuggetOsmium"   , ""		 , 64),
	OSMIUM_CLUMP	 ("osmium_clump"	 , EnumRarity.UNCOMMON, "clumpOsmium"	, ""		 , 64),
	OSMIUM_INGOT	 ("osmium_ingot"	 , EnumRarity.UNCOMMON, "ingotOsmium"	, ""		 , 64),
	OSMIUM_ROD	   ("osmium_rod"	   , EnumRarity.UNCOMMON, "stickOsmium"	, "rodOsmium", 64),
	OSMIUM_GEAR	  ("osmium_gear"	  , EnumRarity.UNCOMMON, "gearOsmium"	 , ""		 , 64),
	OSMIUM_PLATE	 ("osmium_plate"	 , EnumRarity.UNCOMMON, "plateOsmium"	, ""		 , 64),

	OPEN_0031  ("open"	   , EnumRarity.COMMON, ""		  , ""		, 64),
	OPEN_0032  ("open"	   , EnumRarity.COMMON, ""		  , ""		, 64),
	OPEN_0033  ("open"	   , EnumRarity.COMMON, ""		  , ""		, 64),
	OPEN_0034  ("open"	   , EnumRarity.COMMON, ""		  , ""		, 64),
	OPEN_0035  ("open"	   , EnumRarity.COMMON, ""		  , ""		, 64),
	OPEN_0036  ("open"	   , EnumRarity.COMMON, ""		  , ""		, 64),
	INVAR_CLUMP("invar_clump", EnumRarity.COMMON, "clumpInvar", ""		, 64),
	INVAR_INGOT("invar_ingot", EnumRarity.COMMON, "ingotInvar", ""		, 64),
	INVAR_ROD  ("invar_rod"  , EnumRarity.COMMON, "stickInvar", "rodInvar", 64),
	INVAR_GEAR ("invar_gear" , EnumRarity.COMMON, "gearInvar" , ""		, 64),
	INVAR_PLATE("invar_plate", EnumRarity.COMMON, "plateInvar", ""		, 64),

	OPEN_0037   ("open"		, EnumRarity.COMMON, ""		   , ""		 , 64),
	OPEN_0038   ("open"		, EnumRarity.COMMON, ""		   , ""		 , 64),
	OPEN_0039   ("open"		, EnumRarity.COMMON, ""		   , ""		 , 64),
	OPEN_0040   ("open"		, EnumRarity.COMMON, ""		   , ""		 , 64),
	OPEN_0041   ("open"		, EnumRarity.COMMON, ""		   , ""		 , 64),
	OPEN_0042   ("open"		, EnumRarity.COMMON, ""		   , ""		 , 64),
	BRONZE_CLUMP("bronze_clump", EnumRarity.COMMON, "clumpBronze", ""		 , 64),
	BRONZE_INGOT("bronze_ingot", EnumRarity.COMMON, "ingotBronze", ""		 , 64),
	BRONZE_ROD  ("bronze_rod"  , EnumRarity.COMMON, "stickBronze", "rodBronze", 64),
	BRONZE_GEAR ("bronze_gear" , EnumRarity.COMMON, "gearBronze" , ""		 , 64),
	BRONZE_PLATE("bronze_plate", EnumRarity.COMMON, "plateBronze", ""		 , 64),

	OPEN_0043  ("open"	   , EnumRarity.COMMON, ""		  , ""		, 64),
	OPEN_0044  ("open"	   , EnumRarity.COMMON, ""		  , ""		, 64),
	OPEN_0045  ("open"	   , EnumRarity.COMMON, ""		  , ""		, 64),
	OPEN_0046  ("open"	   , EnumRarity.COMMON, ""		  , ""		, 64),
	OPEN_0047  ("open"	   , EnumRarity.COMMON, ""		  , ""		, 64),
	OPEN_0048  ("open"	   , EnumRarity.COMMON, ""		  , ""		, 64),
	STEEL_CLUMP("steel_clump", EnumRarity.COMMON, "clumpSteel", ""		, 64),
	STEEL_INGOT("steel_ingot", EnumRarity.COMMON, "ingotSteel", ""		, 64),
	STEEL_ROD  ("steel_rod"  , EnumRarity.COMMON, "stickSteel", "rodSteel", 64),
	STEEL_GEAR ("steel_gear" , EnumRarity.COMMON, "gearSteel" , ""		, 64),
	STEEL_PLATE("steel_plate", EnumRarity.COMMON, "plateSteel", ""		, 64),

	OPEN_0049	   ("open"			, EnumRarity.COMMON, ""			   , ""			 , 64),
	OPEN_0050	   ("open"			, EnumRarity.COMMON, ""			   , ""			 , 64),
	OPEN_0051	   ("open"			, EnumRarity.COMMON, ""			   , ""			 , 64),
	OPEN_0052	   ("open"			, EnumRarity.COMMON, ""			   , ""			 , 64),
	OPEN_0053	   ("open"			, EnumRarity.COMMON, ""			   , ""			 , 64),
	OPEN_0054	   ("open"			, EnumRarity.COMMON, ""			   , ""			 , 64),
	CONSTANTAN_CLUMP("constantan_clump", EnumRarity.COMMON, "clumpConstantan", ""			 , 64),
	CONSTANTAN_INGOT("constantan_ingot", EnumRarity.COMMON, "ingotConstantan", ""			 , 64),
	CONSTANTAN_ROD  ("constantan_rod"  , EnumRarity.COMMON, "stickConstantan", "rodConstantan", 64),
	CONSTANTAN_GEAR ("constantan_gear" , EnumRarity.COMMON, "gearConstantan" , ""			 , 64),
	CONSTANTAN_PLATE("constantan_plate", EnumRarity.COMMON, "plateConstantan", ""			 , 64),

	OPEN_0055	 ("open"		  , EnumRarity.COMMON  , ""			 , ""		   , 64),
	OPEN_0056	 ("open"		  , EnumRarity.COMMON  , ""			 , ""		   , 64),
	OPEN_0057	 ("open"		  , EnumRarity.COMMON  , ""			 , ""		   , 64),
	OPEN_0058	 ("open"		  , EnumRarity.COMMON  , ""			 , ""		   , 64),
	OPEN_0059	 ("open"		  , EnumRarity.COMMON  , ""			 , ""		   , 64),
	OPEN_0060	 ("open"		  , EnumRarity.COMMON  , ""			 , ""		   , 64),
	ELECTRUM_CLUMP("electrum_clump", EnumRarity.UNCOMMON, "clumpElectrum", ""		   , 64),
	ELECTRUM_INGOT("electrum_ingot", EnumRarity.UNCOMMON, "ingotElectrum", ""		   , 64),
	ELECTRUM_ROD  ("electrum_rod"  , EnumRarity.UNCOMMON, "stickElectrum", "rodElectrum", 64),
	ELECTRUM_GEAR ("electrum_gear" , EnumRarity.UNCOMMON, "gearElectrum" , ""		   , 64),
	ELECTRUM_PLATE("electrum_plate", EnumRarity.UNCOMMON, "plateElectrum", ""		   , 64),

	OPEN_0061				 ("open"					  , EnumRarity.COMMON, ""					   , ""					 , 64),
	OPEN_0062				 ("open"					  , EnumRarity.COMMON, ""					   , ""					 , 64),
	OPEN_0063				 ("open"					  , EnumRarity.COMMON, ""					   , ""					 , 64),
	OPEN_0064				 ("open"					  , EnumRarity.COMMON, ""					   , ""					 , 64),
	OPEN_0065				 ("open"					  , EnumRarity.COMMON, ""					   , ""					 , 64),
	OPEN_0066				 ("open"					  , EnumRarity.COMMON, ""					   , ""					 , 64),
	QUARTZ_ENRICHED_IRON_CLUMP("quartz_enriched_iron_clump", EnumRarity.RARE  , "clumpQuartzEnrichedIron", ""					 , 64),
	QUARTZ_ENRICHED_IRON_INGOT("quartz_enriched_iron_ingot", EnumRarity.EPIC  , "ingotQuartzEnrichedIron", ""					 , 64),
	QUARTZ_ENRICHED_IRON_ROD  ("quartz_enriched_iron_rod"  , EnumRarity.RARE  , "stickQuartzEnrichedIron", "rodQuartzEnrichedIron", 64),
	OPEN_0067				 ("open"					  , EnumRarity.COMMON, ""					   , ""					 , 64),
	QUARTZ_ENRICHED_IRON_PLATE("quartz_enriched_iron_plate", EnumRarity.RARE  , "plateQuartzEnrichedIron", ""					 , 64),

	OPEN_0068	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	OPEN_0069	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	OPEN_0070	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	ARDITE_CRYSTAL("ardite_crystal", EnumRarity.EPIC  , "crystalArdite", "", 64),
	ARDITE_SHARD  ("ardite_shard"  , EnumRarity.EPIC  , "shardArdite"  , "", 64),
	OPEN_0071	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	ARDITE_CLUMP  ("ardite_clump"  , EnumRarity.EPIC  , "clumpArdite"  , "", 64),
	OPEN_0072	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	OPEN_0073	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	OPEN_0074	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	ARDITE_PLATE  ("ardite_plate"  , EnumRarity.EPIC  , "plateArdite"  , "", 64),

	OPEN_0075	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	OPEN_0076	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	OPEN_0077	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	COBALT_CRYSTAL("cobalt_crystal", EnumRarity.EPIC  , "crystalCobalt", "", 64),
	COBALT_SHARD  ("cobalt_shard"  , EnumRarity.EPIC  , "shardCobalt"  , "", 64),
	OPEN_0078	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	COBALT_CLUMP  ("cobalt_clump"  , EnumRarity.EPIC  , "clumpCobalt"  , "", 64),
	OPEN_0079	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	OPEN_0080	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	OPEN_0081	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	COBALT_PLATE  ("cobalt_plate"  , EnumRarity.EPIC  , "plateCobalt"  , "", 64),

	OPEN_0082	  ("open"		   , EnumRarity.COMMON, ""			  , ""		  , 64),
	OPEN_0083	  ("open"		   , EnumRarity.COMMON, ""			  , ""		  , 64),
	OPEN_0084	  ("open"		   , EnumRarity.COMMON, ""			  , ""		  , 64),
	IRIDIUM_CRYSTAL("iridium_crystal", EnumRarity.EPIC  , "crystalIridium", ""		  , 64),
	IRIDIUM_SHARD  ("iridium_shard"  , EnumRarity.EPIC  , "shardIridium"  , ""		  , 64),
	IRIDIUM_NUGGET ("iridium_nugget" , EnumRarity.EPIC  , "nuggetIridium" , ""		  , 64),
	IRIDIUM_CLUMP  ("iridium_clump"  , EnumRarity.EPIC  , "clumpIridium"  , ""		  , 64),
	IRIDIUM_INGOT  ("iridium_ingot"  , EnumRarity.EPIC  , "ingotIridium"  , ""		  , 64),
	IRIDIUM_ROD	("iridium_rod"	, EnumRarity.EPIC  , "stickIridium"  , "rodIridium", 64),
	IRIDIUM_GEAR   ("iridium_gear"   , EnumRarity.EPIC  , "gearIridium"   , ""		  , 64),
	IRIDIUM_PLATE  ("iridium_plate"  , EnumRarity.EPIC  , "plateIridium"  , ""		  , 64),

	OPEN_0085		("open"			 , EnumRarity.COMMON, ""				, ""			, 64),
	OPEN_0086		("open"			 , EnumRarity.COMMON, ""				, ""			, 64),
	OPEN_0087		("open"			 , EnumRarity.COMMON, ""				, ""			, 64),
	DRACONIUM_CRYSTAL("draconium_crystal", EnumRarity.EPIC  , "crystalDraconium", ""			, 64),
	DRACONIUM_SHARD  ("draconium_shard"  , EnumRarity.EPIC  , "shardDraconium"  , ""			, 64),
	DRACONIUM_NUGGET ("draconium_nugget" , EnumRarity.EPIC  , "nuggetDraconium" , ""			, 64),
	DRACONIUM_CLUMP  ("draconium_clump"  , EnumRarity.EPIC  , "clumpDraconium"  , ""			, 64),
	DRACONIUM_INGOT  ("draconium_ingot"  , EnumRarity.EPIC  , "ingotDraconium"  , ""			, 64),
	DRACONIUM_ROD	("draconium_rod"	, EnumRarity.EPIC  , "stickDraconium"  , "rodDraconium", 64),
	DRACONIUM_GEAR   ("draconium_gear"   , EnumRarity.EPIC  , "gearDraconium"   , ""			, 64),
	DRACONIUM_PLATE  ("draconium_plate"  , EnumRarity.EPIC  , "plateDraconium"  , ""			, 64),

	OPEN_0088				("open"					 , EnumRarity.COMMON, ""					   , ""					, 64),
	OPEN_0089				("open"					 , EnumRarity.COMMON, ""					   , ""					, 64),
	OPEN_0090				("open"					 , EnumRarity.COMMON, ""					   , ""					, 64),
	OPEN_0091				("open"					 , EnumRarity.COMMON, ""					   , ""					, 64),
	OPEN_0092				("open"					 , EnumRarity.COMMON, ""					   , ""					, 64),
	AWAKENED_DRACONIUM_NUGGET("awakened_draconium_nugget", EnumRarity.EPIC  , "nuggetDraconiumAwakened", ""					, 64),
	AWAKENED_DRACONIUM_CLUMP ("awakened_draconium_clump" , EnumRarity.EPIC  , "clumpDraconiumAwakened" , ""					, 64),
	AWAKENED_DRACONIUM_INGOT ("awakened_draconium_ingot" , EnumRarity.EPIC  , "ingotDraconiumAwakened" , ""					, 64),
	AWAKENED_DRACONIUM_ROD   ("awakened_draconium_rod"   , EnumRarity.EPIC  , "stickDraconiumAwakened" , "rodDraconiumAwakened", 64),
	AWAKENED_DRACONIUM_GEAR  ("awakened_draconium_gear"  , EnumRarity.EPIC  , "gearDraconiumAwakened"  , ""					, 64),
	AWAKENED_DRACONIUM_PLATE ("awakened_draconium_plate" , EnumRarity.EPIC  , "plateDraconiumAwakened" , ""					, 64),

	OPEN_0093			  ("open"				   , EnumRarity.COMMON, ""					 , "", 64),
	OPEN_0094			  ("open"				   , EnumRarity.COMMON, ""					 , "", 64),
	OPEN_0095			  ("open"				   , EnumRarity.COMMON, ""					 , "", 64),
	OPEN_0096			  ("open"				   , EnumRarity.COMMON, ""					 , "", 64),
	OPEN_0097			  ("open"				   , EnumRarity.COMMON, ""					 , "", 64),
	ELECTRICAL_STEEL_NUGGET("electrical_steel_nugget", EnumRarity.EPIC  , "nuggetElectricalSteel", "", 64),
	ELECTRICAL_STEEL_CLUMP ("electrical_steel_clump" , EnumRarity.EPIC  , "clumpElectricalSteel" , "", 64),
	ELECTRICAL_STEEL_INGOT ("electrical_steel_ingot" , EnumRarity.EPIC  , "ingotElectricalSteel" , "", 64),
	OPEN_0098			  ("open"				   , EnumRarity.COMMON, ""					 , "", 64),
	OPEN_0099			  ("open"				   , EnumRarity.COMMON, ""					 , "", 64),
	ELECTRICAL_STEEL_PLATE ("electrical_steel_plate" , EnumRarity.EPIC  , "plateElectricalSteel" , "", 64),

	OPEN_0100			 ("open"				  , EnumRarity.COMMON, ""					, "", 64),
	OPEN_0101			 ("open"				  , EnumRarity.COMMON, ""					, "", 64),
	OPEN_0102			 ("open"				  , EnumRarity.COMMON, ""					, "", 64),
	OPEN_0103			 ("open"				  , EnumRarity.COMMON, ""					, "", 64),
	OPEN_0104			 ("open"				  , EnumRarity.COMMON, ""					, "", 64),
	ENERGETIC_ALLOY_NUGGET("energetic_alloy_nugget", EnumRarity.EPIC  , "nuggetEnergeticAlloy", "", 64),
	ENERGETIC_ALLOY_CLUMP ("energetic_alloy_clump" , EnumRarity.EPIC  , "clumpEnergeticAlloy" , "", 64),
	ENERGETIC_ALLOY_INGOT ("energetic_alloy_ingot" , EnumRarity.EPIC  , "ingotEnergeticAlloy" , "", 64),
	OPEN_0105			 ("open"				  , EnumRarity.COMMON, ""					, "", 64),
	OPEN_0106			 ("open"				  , EnumRarity.COMMON, ""					, "", 64),
	ENERGETIC_ALLOY_PLATE ("energetic_alloy_plate" , EnumRarity.EPIC  , "plateEnergeticAlloy" , "", 64),

	OPEN_0107		   ("open"				, EnumRarity.COMMON, ""				  , "", 64),
	OPEN_0108		   ("open"				, EnumRarity.COMMON, ""				  , "", 64),
	OPEN_0109		   ("open"				, EnumRarity.COMMON, ""				  , "", 64),
	OPEN_0110		   ("open"				, EnumRarity.COMMON, ""				  , "", 64),
	OPEN_0111		   ("open"				, EnumRarity.COMMON, ""				  , "", 64),
	VIBRANT_ALLOY_NUGGET("vibrant_alloy_nugget", EnumRarity.EPIC  , "nuggetVibrantAlloy", "", 64),
	VIBRANT_ALLOY_CLUMP ("vibrant_alloy_clump" , EnumRarity.EPIC  , "clumpVibrantAlloy" , "", 64),
	VIBRANT_ALLOY_INGOT ("vibrant_alloy_ingot" , EnumRarity.EPIC  , "ingotVibrantAlloy" , "", 64),
	OPEN_0112		   ("open"				, EnumRarity.COMMON, ""				  , "", 64),
	OPEN_0113		   ("open"				, EnumRarity.COMMON, ""				  , "", 64),
	VIBRANT_ALLOY_PLATE ("vibrant_alloy_plate" , EnumRarity.EPIC  , "plateVibrantAlloy" , "", 64),

	OPEN_0114			("open"				 , EnumRarity.COMMON, ""				   , "", 64),
	OPEN_0115			("open"				 , EnumRarity.COMMON, ""				   , "", 64),
	OPEN_0116			("open"				 , EnumRarity.COMMON, ""				   , "", 64),
	OPEN_0117			("open"				 , EnumRarity.COMMON, ""				   , "", 64),
	OPEN_0118			("open"				 , EnumRarity.COMMON, ""				   , "", 64),
	REDSTONE_ALLOY_NUGGET("redstone_alloy_nugget", EnumRarity.EPIC  , "nuggetRedstoneAlloy", "", 64),
	REDSTONE_ALLOY_CLUMP ("redstone_alloy_clump" , EnumRarity.EPIC  , "clumpRedstoneAlloy" , "", 64),
	REDSTONE_ALLOY_INGOT ("redstone_alloy_ingot" , EnumRarity.EPIC  , "ingotRedstoneAlloy" , "", 64),
	OPEN_0119			("open"				 , EnumRarity.COMMON, ""				   , "", 64),
	OPEN_0120			("open"				 , EnumRarity.COMMON, ""				   , "", 64),
	REDSTONE_ALLOY_PLATE ("redstone_alloy_plate" , EnumRarity.EPIC  , "plateRedstoneAlloy" , "", 64),

	OPEN_0121			 ("open"				  , EnumRarity.COMMON, ""					, "", 64),
	OPEN_0122			 ("open"				  , EnumRarity.COMMON, ""					, "", 64),
	OPEN_0123			 ("open"				  , EnumRarity.COMMON, ""					, "", 64),
	OPEN_0124			 ("open"				  , EnumRarity.COMMON, ""					, "", 64),
	OPEN_0125			 ("open"				  , EnumRarity.COMMON, ""					, "", 64),
	CONDUCTIVE_IRON_NUGGET("conductive_iron_nugget", EnumRarity.EPIC  , "nuggetConductiveIron", "", 64),
	CONDUCTIVE_IRON_CLUMP ("conductive_iron_clump" , EnumRarity.EPIC  , "clumpConductiveIron" , "", 64),
	CONDUCTIVE_IRON_INGOT ("conductive_iron_ingot" , EnumRarity.EPIC  , "ingotConductiveIron" , "", 64),
	OPEN_0126			 ("open"				  , EnumRarity.COMMON, ""					, "", 64),
	OPEN_0127			 ("open"				  , EnumRarity.COMMON, ""					, "", 64),
	CONDUCTIVE_IRON_PLATE ("conductive_iron_plate" , EnumRarity.EPIC  , "plateConductiveIron" , "", 64),

	OPEN_0128			("open"				 , EnumRarity.COMMON, ""				   , "", 64),
	OPEN_0129			("open"				 , EnumRarity.COMMON, ""				   , "", 64),
	OPEN_0130			("open"				 , EnumRarity.COMMON, ""				   , "", 64),
	OPEN_0131			("open"				 , EnumRarity.COMMON, ""				   , "", 64),
	OPEN_0132			("open"				 , EnumRarity.COMMON, ""				   , "", 64),
	PULSATING_IRON_NUGGET("pulsating_iron_nugget", EnumRarity.EPIC  , "nuggetPulsatingIron", "", 64),
	PULSATING_IRON_CLUMP ("pulsating_iron_clump" , EnumRarity.EPIC  , "clumpPulsatingIron" , "", 64),
	PULSATING_IRON_INGOT ("pulsating_iron_ingot" , EnumRarity.EPIC  , "ingotPulsatingIron" , "", 64),
	OPEN_0133			("open"				 , EnumRarity.COMMON, ""				   , "", 64),
	OPEN_0134			("open"				 , EnumRarity.COMMON, ""				   , "", 64),
	PULSATING_IRON_PLATE ("pulsating_iron_plate" , EnumRarity.EPIC  , "platePulsatingIron" , "", 64),

	OPEN_0135		("open"			 , EnumRarity.COMMON, ""			   , "", 64),
	OPEN_0136		("open"			 , EnumRarity.COMMON, ""			   , "", 64),
	OPEN_0137		("open"			 , EnumRarity.COMMON, ""			   , "", 64),
	OPEN_0138		("open"			 , EnumRarity.COMMON, ""			   , "", 64),
	OPEN_0139		("open"			 , EnumRarity.COMMON, ""			   , "", 64),
	DARK_STEEL_NUGGET("dark_steel_nugget", EnumRarity.EPIC  , "nuggetDarkSteel", "", 64),
	DARK_STEEL_CLUMP ("dark_steel_clump" , EnumRarity.EPIC  , "clumpDarkSteel" , "", 64),
	DARK_STEEL_INGOT ("dark_steel_ingot" , EnumRarity.EPIC  , "ingotDarkSteel" , "", 64),
	OPEN_0140		("open"			 , EnumRarity.COMMON, ""			   , "", 64),
	OPEN_0141		("open"			 , EnumRarity.COMMON, ""			   , "", 64),
	DARK_STEEL_PLATE ("dark_steel_plate" , EnumRarity.EPIC  , "plateDarkSteel" , "", 64),

	OPEN_0142	   ("open"			, EnumRarity.COMMON, ""			   , "", 64),
	OPEN_0143	   ("open"			, EnumRarity.COMMON, ""			   , "", 64),
	OPEN_0144	   ("open"			, EnumRarity.COMMON, ""			   , "", 64),
	OPEN_0145	   ("open"			, EnumRarity.COMMON, ""			   , "", 64),
	OPEN_0146	   ("open"			, EnumRarity.COMMON, ""			   , "", 64),
	SOULARIUM_NUGGET("soularium_nugget", EnumRarity.EPIC  , "nuggetSoularium", "", 64),
	SOULARIUM_CLUMP ("soularium_clump" , EnumRarity.EPIC  , "clumpSoularium" , "", 64),
	SOULARIUM_INGOT ("soularium_ingot" , EnumRarity.EPIC  , "ingotSoularium" , "", 64),
	OPEN_0147	   ("open"			, EnumRarity.COMMON, ""			   , "", 64),
	OPEN_0148	   ("open"			, EnumRarity.COMMON, ""			   , "", 64),
	SOULARIUM_PLATE ("soularium_plate" , EnumRarity.EPIC  , "plateSoularium" , "", 64),

	OPEN_0149	   ("open"			, EnumRarity.COMMON, ""			  , "", 64),
	OPEN_0150	   ("open"			, EnumRarity.COMMON, ""			  , "", 64),
	OPEN_0151	   ("open"			, EnumRarity.COMMON, ""			  , "", 64),
	OPEN_0152	   ("open"			, EnumRarity.COMMON, ""			  , "", 64),
	OPEN_0153	   ("open"			, EnumRarity.COMMON, ""			  , "", 64),
	END_STEEL_NUGGET("end_steel_nugget", EnumRarity.EPIC  , "nuggetEndSteel", "", 64),
	END_STEEL_CLUMP ("end_steel_clump" , EnumRarity.EPIC  , "clumpEndSteel" , "", 64),
	END_STEEL_INGOT ("end_steel_ingot" , EnumRarity.EPIC  , "ingotEndSteel" , "", 64),
	OPEN_0154	   ("open"			, EnumRarity.COMMON, ""			  , "", 64),
	OPEN_0155	   ("open"			, EnumRarity.COMMON, ""			  , "", 64),
	END_STEEL_PLATE ("end_steel_plate" , EnumRarity.EPIC  , "plateEndSteel" , "", 64),

	OPEN_0156			 ("open"				  , EnumRarity.COMMON, ""					, "", 64),
	OPEN_0157			 ("open"				  , EnumRarity.COMMON, ""					, "", 64),
	OPEN_0158			 ("open"				  , EnumRarity.COMMON, ""					, "", 64),
	OPEN_0159			 ("open"				  , EnumRarity.COMMON, ""					, "", 64),
	OPEN_0160			 ("open"				  , EnumRarity.COMMON, ""					, "", 64),
	OPEN_0161			 ("open"				  , EnumRarity.COMMON, ""					, "", 64),
	OPEN_0162			 ("open"				  , EnumRarity.COMMON, ""					, "", 64),
	OPEN_0163			 ("open"				  , EnumRarity.COMMON, ""					, "", 64),
	OPEN_0164			 ("open"				  , EnumRarity.COMMON, ""					, "", 64),
	OPEN_0165			 ("open"				  , EnumRarity.COMMON, ""					, "", 64),
	REFINED_OBSIDIAN_PLATE("refined_obsidian_plate", EnumRarity.RARE  , "plateRefinedObsidian", "", 64),

	OPEN_0166			  ("open"				   , EnumRarity.COMMON, ""					 , "", 64),
	OPEN_0167			  ("open"				   , EnumRarity.COMMON, ""					 , "", 64),
	OPEN_0168			  ("open"				   , EnumRarity.COMMON, ""					 , "", 64),
	OPEN_0169			  ("open"				   , EnumRarity.COMMON, ""					 , "", 64),
	OPEN_0170			  ("open"				   , EnumRarity.COMMON, ""					 , "", 64),
	OPEN_0171			  ("open"				   , EnumRarity.COMMON, ""					 , "", 64),
	OPEN_0172			  ("open"				   , EnumRarity.COMMON, ""					 , "", 64),
	OPEN_0173			  ("open"				   , EnumRarity.COMMON, ""					 , "", 64),
	OPEN_0174			  ("open"				   , EnumRarity.COMMON, ""					 , "", 64),
	OPEN_0175			  ("open"				   , EnumRarity.COMMON, ""					 , "", 64),
	REFINED_GLOWSTONE_PLATE("refined_glowstone_plate", EnumRarity.RARE  , "plateRefinedGlowstone", "", 64),

	OPEN_0176	("open"		 , EnumRarity.COMMON  , ""			, "", 64),
	OPEN_0177	("open"		 , EnumRarity.COMMON  , ""			, "", 64),
	OPEN_0178	("open"		 , EnumRarity.COMMON  , ""			, "", 64),
	OPEN_0179	("open"		 , EnumRarity.COMMON  , ""			, "", 64),
	OPEN_0180	("open"		 , EnumRarity.COMMON  , ""			, "", 64),
	OPEN_0181	("open"		 , EnumRarity.COMMON  , ""			, "", 64),
	OPEN_0182	("open"		 , EnumRarity.COMMON  , ""			, "", 64),
	OPEN_0183	("open"		 , EnumRarity.COMMON  , ""			, "", 64),
	OPEN_0184	("open"		 , EnumRarity.COMMON  , ""			, "", 64),
	OPEN_0185	("open"		 , EnumRarity.COMMON  , ""			, "", 64),
	SPECTRE_PLATE("spectre_plate", EnumRarity.UNCOMMON, "plateSpectre", "", 64),

	OPEN_0186			("open"				 , EnumRarity.COMMON, "", "", 64),
	OPEN_0187			("open"				 , EnumRarity.COMMON, "", "", 64),
	OPEN_0188			("open"				 , EnumRarity.COMMON, "", "", 64),
	OPEN_0189			("open"				 , EnumRarity.COMMON, "", "", 64),
	OPEN_0190			("open"				 , EnumRarity.COMMON, "", "", 64),
	OPEN_0191			("open"				 , EnumRarity.COMMON, "", "", 64),
	OPEN_B191           ("open"              , EnumRarity.COMMON, "", "", 64),
	OPEN_0192			("open"				 , EnumRarity.COMMON, "", "", 64),
	OPEN_0193			("open"				 , EnumRarity.COMMON, "", "", 64),
	OPEN_0194			("open"				 , EnumRarity.COMMON, "", "", 64),
	OPEN_0195			("open"				 , EnumRarity.COMMON, "", "", 64),

	OPEN_0196			("open"				 , EnumRarity.COMMON, ""				   , "", 64),
	OPEN_0197			("open"				 , EnumRarity.COMMON, ""				   , "", 64),
	OPEN_0198			("open"				 , EnumRarity.COMMON, ""				   , "", 64),
	OPEN_0199			("open"				 , EnumRarity.COMMON, ""				   , "", 64),
	OPEN_0200			("open"				 , EnumRarity.COMMON, ""				   , "", 64),
	OPEN_0201			("open"				 , EnumRarity.COMMON, ""				   , "", 64),
	FLUXED_ELECTRUM_CLUMP("fluxed_electrum_clump", EnumRarity.RARE  , "clumpFluxedElectrum", "", 64),
	OPEN_0202			("open"				 , EnumRarity.COMMON, ""				   , "", 64),
	OPEN_0203			("open"				 , EnumRarity.COMMON, ""				   , "", 64),
	OPEN_0204			("open"				 , EnumRarity.COMMON, ""				   , "", 64),
	OPEN_0205			("open"				 , EnumRarity.COMMON, ""				   , "", 64),

	OPEN_0206	 ("open"		  , EnumRarity.COMMON, ""			, "", 64),
	OPEN_0207	 ("open"		  , EnumRarity.COMMON, ""			, "", 64),
	OPEN_0208	 ("open"		  , EnumRarity.COMMON, ""			, "", 64),
	OPEN_0209	 ("open"		  , EnumRarity.COMMON, ""			, "", 64),
	OPEN_0210	 ("open"		  , EnumRarity.COMMON, ""			, "", 64),
	OPEN_0211	 ("open"		  , EnumRarity.COMMON, ""			, "", 64),
	PIG_IRON_CLUMP("pig_iron_clump", EnumRarity.COMMON, "clumpPigiron", "", 64),
	OPEN_0212	 ("open"		  , EnumRarity.COMMON, ""			, "", 64),
	OPEN_0213	 ("open"		  , EnumRarity.COMMON, ""			, "", 64),
	OPEN_0214	 ("open"		  , EnumRarity.COMMON, ""			, "", 64),
	OPEN_0215	 ("open"		  , EnumRarity.COMMON, ""			, "", 64),

	OPEN_0216		 ("open"			  , EnumRarity.COMMON, ""				, "", 64),
	OPEN_0217		 ("open"			  , EnumRarity.COMMON, ""				, "", 64),
	OPEN_0218		 ("open"			  , EnumRarity.COMMON, ""				, "", 64),
	OPEN_0219		 ("open"			  , EnumRarity.COMMON, ""				, "", 64),
	OPEN_0220		 ("open"			  , EnumRarity.COMMON, ""				, "", 64),
	OPEN_0221		 ("open"			  , EnumRarity.COMMON, ""				, "", 64),
	KNIGHT_SLIME_CLUMP("knight_slime_clump", EnumRarity.COMMON, "clumpKnightslime", "", 64),
	OPEN_0222		 ("open"			  , EnumRarity.COMMON, ""				, "", 64),
	OPEN_0223		 ("open"			  , EnumRarity.COMMON, ""				, "", 64),
	OPEN_0224		 ("open"			  , EnumRarity.COMMON, ""				, "", 64),
	OPEN_0225		 ("open"			  , EnumRarity.COMMON, ""				, "", 64),

	OPEN_0226	  ("open"		   , EnumRarity.COMMON, ""			  , "", 64),
	OPEN_0227	  ("open"		   , EnumRarity.COMMON, ""			  , "", 64),
	OPEN_0228	  ("open"		   , EnumRarity.COMMON, ""			  , "", 64),
	OPEN_0229	  ("open"		   , EnumRarity.COMMON, ""			  , "", 64),
	OPEN_0230	  ("open"		   , EnumRarity.COMMON, ""			  , "", 64),
	OPEN_0231	  ("open"		   , EnumRarity.COMMON, ""			  , "", 64),
	MANYULLYN_CLUMP("manyullyn_clump", EnumRarity.EPIC  , "clumpManyullyn", "", 64),
	OPEN_0232	  ("open"		   , EnumRarity.COMMON, ""			  , "", 64),
	OPEN_0233	  ("open"		   , EnumRarity.COMMON, ""			  , "", 64),
	OPEN_0234	  ("open"		   , EnumRarity.COMMON, ""			  , "", 64),
	MANYULLYN_PLATE("manyullyn_plate", EnumRarity.EPIC  , "plateManyullyn", "", 64),

	OPEN_0235	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	OPEN_0236	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	OPEN_0237	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	OPEN_0238	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	OPEN_0239	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	OPEN_0240	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	SIGNALUM_CLUMP("signalum_clump", EnumRarity.COMMON, "clumpSignalum", "", 64),
	OPEN_0241	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	OPEN_0242	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	OPEN_0243	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	OPEN_0244	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),

	OPEN_0245	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	OPEN_0246	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	OPEN_0247	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	OPEN_0248	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	OPEN_0249	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	OPEN_0250	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	ENDERIUM_CLUMP("enderium_clump", EnumRarity.COMMON, "clumpEnderium", "", 64),
	OPEN_0251	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	OPEN_0252	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	OPEN_0253	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),
	OPEN_0254	 ("open"		  , EnumRarity.COMMON, ""			 , "", 64),

	OPEN_0255   ("open"		, EnumRarity.COMMON, ""		   , "", 64),
	OPEN_0256   ("open"		, EnumRarity.COMMON, ""		   , "", 64),
	OPEN_0257   ("open"		, EnumRarity.COMMON, ""		   , "", 64),
	OPEN_0258   ("open"		, EnumRarity.COMMON, ""		   , "", 64),
	OPEN_0259   ("open"		, EnumRarity.COMMON, ""		   , "", 64),
	OPEN_0260   ("open"		, EnumRarity.COMMON, ""		   , "", 64),
	LUMIUM_CLUMP("lumium_clump", EnumRarity.COMMON, "clumpLumium", "", 64),
	OPEN_0261   ("open"		, EnumRarity.COMMON, ""		   , "", 64),
	OPEN_0262   ("open"		, EnumRarity.COMMON, ""		   , "", 64),
	OPEN_0263   ("open"		, EnumRarity.COMMON, ""		   , "", 64),
	OPEN_0264   ("open"		, EnumRarity.COMMON, ""		   , "", 64),

	OPEN_0265		   ("open"				, EnumRarity.COMMON  , ""			 , "", 64),
	OPEN_0266		   ("open"				, EnumRarity.COMMON  , ""			 , "", 64),
	OPEN_0267		   ("open"				, EnumRarity.COMMON  , ""			 , "", 64),
	OPEN_0268		   ("open"				, EnumRarity.COMMON  , ""			 , "", 64),
	OPEN_0269		   ("open"				, EnumRarity.COMMON  , ""			 , "", 64),
	OPEN_0270		   ("open"				, EnumRarity.COMMON  , ""			 , "", 64),
	ALUMINUM_BRASS_CLUMP("aluminum_brass_clump", EnumRarity.UNCOMMON, "clumpAlubrass", "", 64),
	OPEN_0271		   ("open"				, EnumRarity.COMMON  , ""			 , "", 64),
	OPEN_0272		   ("open"				, EnumRarity.COMMON  , ""			 , "", 64),
	OPEN_0273		   ("open"				, EnumRarity.COMMON  , ""			 , "", 64),
	OPEN_0274		   ("open"				, EnumRarity.COMMON  , ""			 , "", 64),

	OPEN_0275 ("open"	  , EnumRarity.COMMON, ""		 , "", 64),
	OPEN_0276 ("open"	  , EnumRarity.COMMON, ""		 , "", 64),
	OPEN_0277 ("open"	  , EnumRarity.COMMON, ""		 , "", 64),
	OPEN_0278 ("open"	  , EnumRarity.COMMON, ""		 , "", 64),
	OPEN_0279 ("open"	  , EnumRarity.COMMON, ""		 , "", 64),
	OPEN_0280 ("open"	  , EnumRarity.COMMON, ""		 , "", 64),
	OPEN_0281 ("open"	  , EnumRarity.COMMON, ""		 , "", 64),
	OPEN_0282 ("open"	  , EnumRarity.COMMON, ""		 , "", 64),
	OPEN_0283 ("open"	  , EnumRarity.COMMON, ""		 , "", 64),
	WOOD_GEAR ("wood_gear" , EnumRarity.COMMON, "gearWood" , "", 64),
	WOOD_PLATE("wood_plate", EnumRarity.COMMON, "plateWood", "", 64),

	OPEN_0284  ("open"	   , EnumRarity.COMMON, ""		  , "", 64),
	OPEN_0285  ("open"	   , EnumRarity.COMMON, ""		  , "", 64),
	OPEN_0286  ("open"	   , EnumRarity.COMMON, ""		  , "", 64),
	OPEN_0287  ("open"	   , EnumRarity.COMMON, ""		  , "", 64),
	OPEN_0288  ("open"	   , EnumRarity.COMMON, ""		  , "", 64),
	OPEN_0289  ("open"	   , EnumRarity.COMMON, ""		  , "", 64),
	OPEN_0290  ("open"	   , EnumRarity.COMMON, ""		  , "", 64),
	OPEN_0291  ("open"	   , EnumRarity.COMMON, ""		  , "", 64),
	OPEN_0292  ("open"	   , EnumRarity.COMMON, ""		  , "", 64),
	STONE_GEAR ("stone_gear" , EnumRarity.COMMON, "gearStone" , "", 64),
	STONE_PLATE("stone_plate", EnumRarity.COMMON, "plateStone", "", 64),

	OPEN_0293   ("open"		 , EnumRarity.COMMON  , ""			, ""					 , 64),
	DIAMOND_DUST("diamond_dust" , EnumRarity.UNCOMMON, "dustDiamond" , ""					 , 64),
	OPEN_00294  ("open"		 , EnumRarity.COMMON  , ""			, ""					 , 64),
	OPEN_00295  ("open"		 , EnumRarity.COMMON  , ""			, ""					 , 64),
	OPEN_00296  ("open"		 , EnumRarity.COMMON  , ""			, ""					 , 64),
	OPEN_00298  ("open"		 , EnumRarity.COMMON  , ""			, ""					 , 64),
	OPEN_00299  ("open"		 , EnumRarity.COMMON  , ""			, ""					 , 64),
	OPEN_00300  ("open"		 , EnumRarity.COMMON  , ""			, ""					 , 64),
	OPEN_00301  ("open"		 , EnumRarity.COMMON  , ""			, ""					 , 64),
	DIAMOND_GEAR ("diamond_gear" , EnumRarity.UNCOMMON, "gearDiamond" , ""					 , 64),
	DIAMOND_PLATE("diamond_plate", EnumRarity.UNCOMMON, "plateDiamond", "itemCompressedDiamond", 64),

	OPEN_302	 ("open"		 , EnumRarity.COMMON, ""			, "", 64),
	EMERALD_DUST ("emerald_dust" , EnumRarity.RARE  , "dustEmerald" , "", 64),
	OPEN_0303	("open"		 , EnumRarity.COMMON, ""			, "", 64),
	OPEN_0304	("open"		 , EnumRarity.COMMON, ""			, "", 64),
	OPEN_0305	("open"		 , EnumRarity.COMMON, ""			, "", 64),
	OPEN_0306	("open"		 , EnumRarity.COMMON, ""			, "", 64),
	OPEN_0307	("open"		 , EnumRarity.COMMON, ""			, "", 64),
	OPEN_0308	("open"		 , EnumRarity.COMMON, ""			, "", 64),
	OPEN_0309	("open"		 , EnumRarity.COMMON, ""			, "", 64),
	OPEN_0310	("open"		 , EnumRarity.COMMON, ""			, "", 64),
	EMERALD_PLATE("emerald_plate", EnumRarity.RARE  , "plateEmerald", "", 64),

	SULFUR_DUST_TINY("sulfur_dust_tiny", EnumRarity.COMMON, "dustTinySulfur", "", 64),
	SULFUR_DUST	 ("sulfur_dust"	 , EnumRarity.COMMON, "dustSulfur"	, "", 64),
	OPEN_0311	   ("open"			, EnumRarity.COMMON, ""			  , "", 64),
	OPEN_0312	   ("open"			, EnumRarity.COMMON, ""			  , "", 64),
	OPEN_0313	   ("open"			, EnumRarity.COMMON, ""			  , "", 64),
	OPEN_0314	   ("open"			, EnumRarity.COMMON, ""			  , "", 64),
	OPEN_0315	   ("open"			, EnumRarity.COMMON, ""			  , "", 64),
	OPEN_0316	   ("open"			, EnumRarity.COMMON, ""			  , "", 64),
	OPEN_0317	   ("open"			, EnumRarity.COMMON, ""			  , "", 64),
	OPEN_0318	   ("open"			, EnumRarity.COMMON, ""			  , "", 64),
	OPEN_0319	   ("open"			, EnumRarity.COMMON, ""			  , "", 64),

	OPEN_0320  ("open"	   , EnumRarity.COMMON, ""		  , "", 64),
	OPEN_0321  ("open"	   , EnumRarity.COMMON, ""		  , "", 64),
	OPEN_0322  ("open"	   , EnumRarity.COMMON, ""		  , "", 64),
	OPEN_0323  ("open"	   , EnumRarity.COMMON, ""		  , "", 64),
	OPEN_0324  ("open"	   , EnumRarity.COMMON, ""		  , "", 64),
	COAL_NUGGET("coal_nugget", EnumRarity.COMMON, "nuggetCoal", "", 64),
	COAL_CLUMP ("coal_clump" , EnumRarity.COMMON, "smallCoal" , "", 64),
	OPEN_0325  ("open"	   , EnumRarity.COMMON, ""		  , "", 64),
	OPEN_0326  ("open"	   , EnumRarity.COMMON, ""		  , "", 64),
	OPEN_0327  ("open"	   , EnumRarity.COMMON, ""		  , "", 64),
	OPEN_0328  ("open"	   , EnumRarity.COMMON, ""		  , "", 64),

	OPEN_0329	 ("open"		  , EnumRarity.COMMON, ""		, "", 64),
	COAL_COKE_DUST("coal_coke_dust", EnumRarity.COMMON, "dustCoke", "", 64),
	OPEN_0330	 ("open"		  , EnumRarity.COMMON, ""		, "", 64),
	OPEN_0331	 ("open"		  , EnumRarity.COMMON, ""		, "", 64),
	OPEN_0332	 ("open"		  , EnumRarity.COMMON, ""		, "", 64),
	OPEN_0333	 ("open"		  , EnumRarity.COMMON, ""		, "", 64),
	OPEN_0334	 ("open"		  , EnumRarity.COMMON, ""		, "", 64),
	COAL_COKE	 ("coal_coke"	 , EnumRarity.COMMON, "fuelCoke", "", 64),
	OPEN_0335	 ("open"		  , EnumRarity.COMMON, ""		, "", 64),
	OPEN_0336	 ("open"		  , EnumRarity.COMMON, ""		, "", 64),
	OPEN_0337	 ("open"		  , EnumRarity.COMMON, ""		, "", 64),

	OPEN_0338	("open"		 , EnumRarity.COMMON, ""			, "", 64),
	GRAPHITE_DUST("graphite_dust", EnumRarity.COMMON, "dustGraphite", "", 64),
	OPEN_0339	("open"		 , EnumRarity.COMMON, ""			, "", 64),
	OPEN_0340	("open"		 , EnumRarity.COMMON, ""			, "", 64),
	OPEN_0341	("open"		 , EnumRarity.COMMON, ""			, "", 64),
	OPEN_0342	("open"		 , EnumRarity.COMMON, ""			, "", 64),
	OPEN_0343	("open"		 , EnumRarity.COMMON, ""			, "", 64),
	OPEN_0344	("open"		 , EnumRarity.COMMON, ""			, "", 64),
	OPEN_0345	("open"		 , EnumRarity.COMMON, ""			, "", 64),
	OPEN_0346	("open"		 , EnumRarity.COMMON, ""			, "", 64),
	OPEN_0347	("open"		 , EnumRarity.COMMON, ""			, "", 64),

	OPEN_0348		   ("open"				, EnumRarity.COMMON  , ""			  , "", 64),
	URANIUM_DUST		("uranium_dust"		, EnumRarity.UNCOMMON, ""			  , "", 64),
	OPEN_0349		   ("open"				, EnumRarity.COMMON  , ""			  , "", 64),
	URANIUM_PURE_DUST   ("uranium_pure_dust"   , EnumRarity.UNCOMMON, ""			  , "", 64),
	OPEN_0350		   ("open"				, EnumRarity.COMMON  , ""			  , "", 64),
	URANIUM_U235_DUST   ("uranium_u235_dust"   , EnumRarity.UNCOMMON, ""			  , "", 64),
	OPEN_0351		   ("open"				, EnumRarity.COMMON  , ""			  , "", 64),
	URANIUM_U238_DUST   ("uranium_u238_dust"   , EnumRarity.UNCOMMON, ""			  , "", 64),
	OPEN_0352		   ("open"				, EnumRarity.COMMON  , ""			  , "", 64),
	URANIUM_DIOXIDE_DUST("uranium_dioxide_dust", EnumRarity.UNCOMMON, "dustYellorium" , "", 64),
	OPEN_0353		   ("open"				, EnumRarity.COMMON  , ""			  , "", 64),
	OPEN_0354		   ("open"				, EnumRarity.COMMON  , ""			  , "", 64),
	OPEN_0355		   ("open"				, EnumRarity.COMMON  , ""			  , "", 64),
	OPEN_0356		   ("open"				, EnumRarity.COMMON  , ""			  , "", 64),
	OPEN_0357		   ("open"				, EnumRarity.COMMON  , ""			  , "", 64),
	URANIUM_INGOT	   ("uranium_ingot"	   , EnumRarity.UNCOMMON, "ingotYellorium", "", 64),
	OPEN_0358		   ("open"				, EnumRarity.COMMON  , ""			  , "", 64),
	OPEN_0359		   ("open"				, EnumRarity.COMMON  , ""			  , "", 64),
	OPEN_0360		   ("open"				, EnumRarity.COMMON  , ""			  , "", 64),

	OPEN_0361	 ("open", EnumRarity.COMMON, "", "", 64),
	OPEN_0362	 ("open", EnumRarity.COMMON, "", "", 64),
	OPEN_0363	 ("open", EnumRarity.COMMON, "", "", 64),
	OPEN_0364	 ("open", EnumRarity.COMMON, "", "", 64),
	OPEN_0365	 ("open", EnumRarity.COMMON, "", "", 64),
	OPEN_0366	 ("open", EnumRarity.COMMON, "", "", 64),
	OPEN_0367	 ("open", EnumRarity.COMMON, "", "", 64),
	OPEN_0368	 ("open", EnumRarity.COMMON, "", "", 64),
	OPEN_0369	 ("open", EnumRarity.COMMON, "", "", 64),
	OPEN_0370	 ("open", EnumRarity.COMMON, "", "", 64),

	SLAG("slag", EnumRarity.COMMON, "crystalSlag", "itemSlag", 64),

	OPEN_0371	 ("open", EnumRarity.COMMON, "", "", 64),
	OPEN_0372	 ("open", EnumRarity.COMMON, "", "", 64),
	OPEN_0373	 ("open", EnumRarity.COMMON, "", "", 64),
	OPEN_0374	 ("open", EnumRarity.COMMON, "", "", 64),
	OPEN_0375	 ("open", EnumRarity.COMMON, "", "", 64),
	OPEN_0376	 ("open", EnumRarity.COMMON, "", "", 64),
	OPEN_0377	 ("open", EnumRarity.COMMON, "", "", 64),
	OPEN_0378	 ("open", EnumRarity.COMMON, "", "", 64),
	OPEN_0379	 ("open", EnumRarity.COMMON, "", "", 64),
	OPEN_0380	 ("open", EnumRarity.COMMON, "", "", 64),

	NETHER_KEY("nether_key", EnumRarity.RARE, "", "", 1),
	END_KEY   ("end_key"   , EnumRarity.EPIC, "", "", 1);

	private String name;
	private EnumRarity rarity;
	private String recipeOreDict1;
	private String recipeOreDict2;
 	private int maxSize;

	EnumMaterials(String name, EnumRarity rarity, String recipeOreDict1, String recipeOreDict2, int maxSize) {
		this.name = name;
		this.rarity = rarity;
		this.recipeOreDict1 = recipeOreDict1;
		this.recipeOreDict2 = recipeOreDict2;
		this.maxSize = maxSize;
	}

	public int getMaxSize() {
 		return maxSize;
 	}

	@Override
	public String getName() {
		return name;
	}

	public String getRecipeOreDict1() {
		return recipeOreDict1;
	}

	public String getRecipeOreDict2() {
		return recipeOreDict2;
	}

	public EnumRarity getRarity() {
		return rarity;
	}

}