package mctmods.basemod.items.meta;

import net.minecraft.item.EnumRarity;
import net.minecraft.util.IStringSerializable;

public enum EnumMaterials implements IStringSerializable {

	IRON_CRUSHED_ORE("iron_crushed_ore"	,EnumRarity.COMMON,"crushedIron"	,""			,64),
	IRON_DUST		("iron_dust"		,EnumRarity.COMMON,"dustIron"		,""			,64),
	IRON_DUST_DIRTY	("iron_dust_dirty"	,EnumRarity.COMMON,"dustDirtyIron"	,""			,64),
	OPEN_0001		("open"				,EnumRarity.COMMON,""				,""			,64),
	IRON_SHARD		("iron_shard"		,EnumRarity.COMMON,"shardIron"		,""			,64),
	OPEN_0002		("open"				,EnumRarity.COMMON,""				,""			,64),
	IRON_CLUMP		("iron_clump"		,EnumRarity.COMMON,"clumpIron"		,""			,64),
	OPEN_0003		("open"				,EnumRarity.COMMON,""				,""			,64),
	IRON_ROD		("iron_rod"			,EnumRarity.COMMON,"stickIron"		,"rodIron"	,64),
	IRON_GEAR		("iron_gear"		,EnumRarity.COMMON,"gearIron"		,""			,64),
	IRON_PLATE		("iron_plate"		,EnumRarity.COMMON,"plateIron"		,""			,64),

	GOLD_CRUSHED_ORE("gold_crushed_ore"	,EnumRarity.COMMON,"crushedGold"	,""			,64),
	GOLD_DUST		("gold_dust"		,EnumRarity.COMMON,"dustGold"		,""			,64),
	GOLD_DUST_DIRTY	("gold_dust_dirty"	,EnumRarity.COMMON,"dustDirtyGold"	,""			,64),
	OPEN_0010		("open"				,EnumRarity.COMMON,""				,""			,64),
	GOLD_SHARD		("gold_shard"		,EnumRarity.COMMON,"shardGold"		,""			,64),
	OPEN_0011		("open"				,EnumRarity.COMMON,""				,""			,64),
	GOLD_CLUMP		("gold_clump"		,EnumRarity.COMMON,"clumpGold"		,""			,64),
	OPEN_0012		("open"				,EnumRarity.COMMON,""				,""			,64),
	GOLD_ROD		("gold_rod"			,EnumRarity.COMMON,"stickGold"		,"rodGold"	,64),
	GOLD_GEAR		("gold_gear"		,EnumRarity.COMMON,"gearGold"		,""			,64),
	GOLD_PLATE		("gold_plate"		,EnumRarity.COMMON,"plateGold"		,""			,64),

	COPPER_CRUSHED_ORE	("copper_crushed_ore"	,EnumRarity.COMMON,"crushedCopper"	,""			,64),
	COPPER_DUST			("copper_dust"			,EnumRarity.COMMON,"dustCopper"		,""			,64),
	COPPER_DUST_DIRTY	("copper_dust_dirty"	,EnumRarity.COMMON,"dustDirtyCopper",""			,64),
	OPEN_0020			("open"					,EnumRarity.COMMON,""				,""			,64),
	COPPER_SHARD		("copper_shard"			,EnumRarity.COMMON,"shardCopper"	,""			,64),
	COPPER_NUGGET		("copper_nugget"		,EnumRarity.COMMON,"nuggetCopper"	,""			,64),
	COPPER_CLUMP		("copper_clump"			,EnumRarity.COMMON,"clumpCopper"	,""			,64),
	COPPER_INGOT		("copper_ingot"			,EnumRarity.COMMON,"ingotCopper"	,""			,64),
	COPPER_ROD			("copper_rod"			,EnumRarity.COMMON,"stickCopper"	,"rodCopper",64),
	COPPER_GEAR			("copper_gear"			,EnumRarity.COMMON,"gearCopper"		,""			,64),
	COPPER_PLATE		("copper_plate"			,EnumRarity.COMMON,"plateCopper"	,""			,64),

	TIN_CRUSHED_ORE	("tin_crushed_ore"	,EnumRarity.COMMON,"crushedTin"		,""			,64),
	TIN_DUST		("tin_dust"			,EnumRarity.COMMON,"dustTin"		,""			,64),
	TIN_DUST_DIRTY	("tin_dust_dirty"	,EnumRarity.COMMON,"dustDirtyTin"	,""			,64),
	OPEN_0030		("open"				,EnumRarity.COMMON,""				,""			,64),
	TIN_SHARD		("tin_shard"		,EnumRarity.COMMON,"shardTin"		,""			,64),
	TIN_NUGGET		("tin_nugget"		,EnumRarity.COMMON,"nuggetTin"		,""			,64),
	TIN_CLUMP		("tin_clump"		,EnumRarity.COMMON,"clumpTin"		,""			,64),
	TIN_INGOT		("tin_ingot"		,EnumRarity.COMMON,"ingotTin"		,""			,64),
	TIN_ROD			("tin_rod"			,EnumRarity.COMMON,"stickTin"		,"rodTin"	,64),
	TIN_GEAR		("tin_gear"			,EnumRarity.COMMON,"gearTin"		,""			,64),
	TIN_PLATE		("tin_plate"		,EnumRarity.COMMON,"plateTin"		,""			,64),

	NICKEL_CRUSHED_ORE	("nickel_crushed_ore"	,EnumRarity.COMMON,"crushedNickel"	,""			,64),
	NICKEL_DUST			("nickel_dust"			,EnumRarity.COMMON,"dustNickel"		,""			,64),
	NICKEL_DUST_DIRTY	("nickel_dust_dirty"	,EnumRarity.COMMON,"dustDirtyNickel",""			,64),
	OPEN_0040			("open"					,EnumRarity.COMMON,""				,""			,64),
	NICKEL_SHARD		("nickel_shard"			,EnumRarity.COMMON,"shardNickel"	,""			,64),
	NICKEL_NUGGET		("nickel_nugget"		,EnumRarity.COMMON,"nuggetNickel"	,""			,64),
	NICKEL_CLUMP		("nickel_clump"			,EnumRarity.COMMON,"clumpNickel"	,""			,64),
	NICKEL_INGOT		("nickel_ingot"			,EnumRarity.COMMON,"ingotNickel"	,""			,64),
	NICKEL_ROD			("nickel_rod"			,EnumRarity.COMMON,"stickNickel"	,"rodNickel",64),
	NICKEL_GEAR			("nickel_gear"			,EnumRarity.COMMON,"gearNickel"		,""			,64),
	NICKEL_PLATE		("nickel_plate"			,EnumRarity.COMMON,"plateNickel"	,""			,64),

	SILVER_CRUSHED_ORE	("silver_crushed_ore"	,EnumRarity.UNCOMMON,"crushedSilver"	,""			,64),
	SILVER_DUST			("silver_dust"			,EnumRarity.UNCOMMON,"dustSilver"		,""			,64),
	SILVER_DUST_DIRTY	("silver_dust_dirty"	,EnumRarity.UNCOMMON,"dustDirtySilver"	,""			,64),
	OPEN_0050			("open"					,EnumRarity.UNCOMMON,""					,""			,64),
	SILVER_SHARD		("silver_shard"			,EnumRarity.UNCOMMON,"shardSilver"		,""			,64),
	SILVER_NUGGET		("silver_nugget"		,EnumRarity.UNCOMMON,"nuggetSilver"		,""			,64),
	SILVER_CLUMP		("silver_clump"			,EnumRarity.UNCOMMON,"clumpSilver"		,""			,64),
	SILVER_INGOT		("silver_ingot"			,EnumRarity.UNCOMMON,"ingotSilver"		,""			,64),
	SILVER_ROD			("silver_rod"			,EnumRarity.UNCOMMON,"stickSilver"		,"rodSilver",64),
	SILVER_GEAR			("silver_gear"			,EnumRarity.UNCOMMON,"gearSilver"		,""			,64),
	SILVER_PLATE		("silver_plate"			,EnumRarity.UNCOMMON,"plateSilver"		,""			,64),

	LEAD_CRUSHED_ORE("lead_crushed_ore"	,EnumRarity.UNCOMMON,"crushedLead"	,""			,64),
	LEAD_DUST		("lead_dust"		,EnumRarity.UNCOMMON,"dustLead"		,""			,64),
	LEAD_DUST_DIRTY	("lead_dust_dirty"	,EnumRarity.UNCOMMON,"dustDirtyLead",""			,64),
	OPEN_0060		("open"				,EnumRarity.UNCOMMON,""				,""			,64),
	LEAD_SHARD		("lead_shard"		,EnumRarity.UNCOMMON,"shardLead"	,""			,64),
	LEAD_NUGGET		("lead_nugget"		,EnumRarity.UNCOMMON,"nuggetLead"	,""			,64),
	LEAD_CLUMP		("lead_clump"		,EnumRarity.UNCOMMON,"clumpLead"	,""			,64),
	LEAD_INGOT		("lead_ingot"		,EnumRarity.UNCOMMON,"ingotLead"	,""			,64),
	LEAD_ROD		("lead_rod"			,EnumRarity.UNCOMMON,"stickLead"	,"rodLead"	,64),
	LEAD_GEAR		("lead_gear"		,EnumRarity.UNCOMMON,"gearLead"		,""			,64),
	LEAD_PLATE		("lead_plate"		,EnumRarity.UNCOMMON,"plateLead"	,""			,64),

	ALUMINUM_CRUSHED_ORE("aluminum_crushed_ore"	,EnumRarity.UNCOMMON,"crushedAluminum"	,""				,64),
	ALUMINUM_DUST		("aluminum_dust"		,EnumRarity.UNCOMMON,"dustAluminum"		,""				,64),
	ALUMINUM_DUST_DIRTY	("aluminum_dust_dirty"	,EnumRarity.UNCOMMON,"dustDirtyAluminum",""				,64),
	OPEN_0070			("open"					,EnumRarity.UNCOMMON,""					,""				,64),
	ALUMINUM_SHARD		("aluminum_shard"		,EnumRarity.UNCOMMON,"shardAluminum"	,""				,64),
	ALUMINUM_NUGGET		("aluminum_nugget"		,EnumRarity.UNCOMMON,"nuggetAluminum"	,""				,64),
	ALUMINUM_CLUMP		("aluminum_clump"		,EnumRarity.UNCOMMON,"clumpAluminum"	,""				,64),
	ALUMINUM_INGOT		("aluminum_ingot"		,EnumRarity.UNCOMMON,"ingotAluminum"	,""				,64),
	ALUMINUM_ROD		("aluminum_rod"			,EnumRarity.UNCOMMON,"stickAluminum"	,"rodAluminum"	,64),
	ALUMINUM_GEAR		("aluminum_gear"		,EnumRarity.UNCOMMON,"gearAluminum"		,""				,64),
	ALUMINUM_PLATE		("aluminum_plate"		,EnumRarity.UNCOMMON,"plateAluminum"	,""				,64),

	OSMIUM_CRUSHED_ORE	("osmium_crushed_ore"	,EnumRarity.UNCOMMON,"crushedOsmium"	,""			,64),
	OSMIUM_DUST			("osmium_dust"			,EnumRarity.UNCOMMON,"dustOsmium"		,""			,64),
	OSMIUM_DUST_DIRTY	("osmium_dust_dirty"	,EnumRarity.UNCOMMON,"dustDirtyOsmium"	,""			,64),
	OPEN_0080			("open"					,EnumRarity.UNCOMMON,""					,""			,64),
	OSMIUM_SHARD		("osmium_shard"			,EnumRarity.UNCOMMON,"shardOsmium"		,""			,64),
	OSMIUM_NUGGET		("osmium_nugget"		,EnumRarity.UNCOMMON,"nuggetOsmium"		,""			,64),
	OSMIUM_CLUMP		("osmium_clump"			,EnumRarity.UNCOMMON,"clumpOsmium"		,""			,64),
	OSMIUM_INGOT		("osmium_ingot"			,EnumRarity.UNCOMMON,"ingotOsmium"		,""			,64),
	OSMIUM_ROD			("osmium_rod"			,EnumRarity.UNCOMMON,"stickOsmium"		,"rodOsmium",64),
	OSMIUM_GEAR			("osmium_gear"			,EnumRarity.UNCOMMON,"gearOsmium"		,""			,64),
	OSMIUM_PLATE		("osmium_plate"			,EnumRarity.UNCOMMON,"plateOsmium"		,""			,64),

	OPEN_0090	("open"			,EnumRarity.COMMON,""			,""			,64),
	INVAR_DUST	("invar_dust"	,EnumRarity.COMMON,"dustInvar"	,""			,64),
	OPEN_0091	("open"			,EnumRarity.COMMON,""			,""			,64),
	OPEN_0092	("open"			,EnumRarity.COMMON,""			,""			,64),
	OPEN_0093	("open"			,EnumRarity.COMMON,""			,""			,64),
	INVAR_NUGGET("invar_nugget"	,EnumRarity.COMMON,"nuggetInvar",""			,64),
	INVAR_CLUMP	("invar_clump"	,EnumRarity.COMMON,"clumpInvar"	,""			,64),
	INVAR_INGOT	("invar_ingot"	,EnumRarity.COMMON,"ingotInvar"	,""			,64),
	INVAR_ROD	("invar_rod"	,EnumRarity.COMMON,"stickInvar"	,"rodInvar"	,64),
	INVAR_GEAR	("invar_gear"	,EnumRarity.COMMON,"gearInvar"	,""			,64),
	INVAR_PLATE	("invar_plate"	,EnumRarity.COMMON,"plateInvar"	,""			,64),

	OPEN_0100		("open"			,EnumRarity.COMMON,""				,""			,64),
	BRONZE_DUST		("bronze_dust"	,EnumRarity.COMMON,"dustBronze"		,""			,64),
	OPEN_0101		("open"			,EnumRarity.COMMON,""				,""			,64),
	OPEN_0102		("open"			,EnumRarity.COMMON,""				,""			,64),
	OPEN_0103		("open"			,EnumRarity.COMMON,""				,""			,64),
	BRONZE_NUGGET	("bronze_nugget",EnumRarity.COMMON,"nuggetBronze"	,""			,64),
	BRONZE_CLUMP	("bronze_clump"	,EnumRarity.COMMON,"clumpBronze"	,""			,64),
	BRONZE_INGOT	("bronze_ingot"	,EnumRarity.COMMON,"ingotBronze"	,""			,64),
	BRONZE_ROD		("bronze_rod"	,EnumRarity.COMMON,"stickBronze"	,"rodBronze",64),
	BRONZE_GEAR		("bronze_gear"	,EnumRarity.COMMON,"gearBronze"		,""			,64),
	BRONZE_PLATE	("bronze_plate"	,EnumRarity.COMMON,"plateBronze"	,""			,64),

	OPEN_0110	("open"			,EnumRarity.COMMON,""			,""			,64),
	STEEL_DUST	("steel_dust"	,EnumRarity.COMMON,"dustSteel"	,""			,64),
	OPEN_0111	("open"			,EnumRarity.COMMON,""			,""			,64),
	OPEN_0112	("open"			,EnumRarity.COMMON,""			,""			,64),
	OPEN_0113	("open"			,EnumRarity.COMMON,""			,""			,64),
	STEEL_NUGGET("steel_nugget"	,EnumRarity.COMMON,"nuggetSteel",""			,64),
	STEEL_CLUMP	("steel_clump"	,EnumRarity.COMMON,"clumpSteel"	,""			,64),
	STEEL_INGOT	("steel_ingot"	,EnumRarity.COMMON,"ingotSteel"	,""			,64),
	STEEL_ROD	("steel_rod"	,EnumRarity.COMMON,"stickSteel"	,"rodSteel"	,64),
	STEEL_GEAR	("steel_gear"	,EnumRarity.COMMON,"gearSteel"	,""			,64),
	STEEL_PLATE	("steel_plate"	,EnumRarity.COMMON,"plateSteel"	,""			,64),

	OPEN_0120			("open"				,EnumRarity.COMMON,""					,""				,64),
	CONSTANTAN_DUST		("constantan_dust"	,EnumRarity.COMMON,"dustContantan"		,""				,64),
	OPEN_0121			("open"				,EnumRarity.COMMON,""					,""				,64),
	OPEN_0122			("open"				,EnumRarity.COMMON,""					,""				,64),
	OPEN_0123			("open"				,EnumRarity.COMMON,""					,""				,64),
	CONSTANTAN_NUGGET	("constantan_nugget",EnumRarity.COMMON,"nuggetConstantan"	,""				,64),
	CONSTANTAN_CLUMP	("constantan_clump"	,EnumRarity.COMMON,"clumpConstantan"	,""				,64),
	CONSTANTAN_INGOT	("constantan_ingot"	,EnumRarity.COMMON,"ingotConstantan"	,""				,64),
	CONSTANTAN_ROD		("constantan_rod"	,EnumRarity.COMMON,"stickConstantan"	,"rodConstantan",64),
	CONSTANTAN_GEAR		("constantan_gear"	,EnumRarity.COMMON,"gearConstantan"		,""				,64),
	CONSTANTAN_PLATE	("constantan_plate"	,EnumRarity.COMMON,"plateConstantan"	,""				,64),

	OPEN_0130		("open"				,EnumRarity.UNCOMMON,""					,""				,64),
	ELECTRUM_DUST	("electrum_dust"	,EnumRarity.UNCOMMON,"dustElectrum"		,""				,64),
	OPEN_0131		("open"				,EnumRarity.UNCOMMON,""					,""				,64),
	OPEN_0132		("open"				,EnumRarity.UNCOMMON,""					,""				,64),
	OPEN_0133		("open"				,EnumRarity.UNCOMMON,""					,""				,64),
	ELECTRUM_NUGGET	("electrum_nugget"	,EnumRarity.UNCOMMON,"nuggetElectrum"	,""				,64),
	ELECTRUM_CLUMP	("electrum_clump"	,EnumRarity.UNCOMMON,"clumpElectrum"	,""				,64),
	ELECTRUM_INGOT	("electrum_ingot"	,EnumRarity.UNCOMMON,"ingotElectrum"	,""				,64),
	ELECTRUM_ROD	("electrum_rod"		,EnumRarity.UNCOMMON,"stickElectrum"	,"rodElectrum"	,64),
	ELECTRUM_GEAR	("electrum_gear"	,EnumRarity.UNCOMMON,"gearElectrum"		,""				,64),
	ELECTRUM_PLATE	("electrum_plate"	,EnumRarity.UNCOMMON,"plateElectrum"	,""				,64),

	OPEN_0140					("open"							,EnumRarity.UNCOMMON,""							,"",64),
	QUARTZ_ENRICHED_IRON_DUST   ("quartz_enriched_iron_dust"	,EnumRarity.UNCOMMON,"dustQuartzEnrichedIron"	,"",64),
	OPEN_0142					("open"							,EnumRarity.UNCOMMON,""							,"",64),
	OPEN_0143					("open"							,EnumRarity.UNCOMMON,""							,"",64),
	OPEN_0144					("open"							,EnumRarity.UNCOMMON,""							,"",64),
	QUARTZ_ENRICHED_IRON_NUGGET	("quartz_enriched_iron_nugget"	,EnumRarity.UNCOMMON,"nuggetQuartzEnrichedIron"	,"",64),
	QUARTZ_ENRICHED_IRON_CLUMP	("quartz_enriched_iron_clump"	,EnumRarity.UNCOMMON,"clumpQuartzEnrichedIron"	,"",64),
	QUARTZ_ENRICHED_IRON_INGOT	("quartz_enriched_iron_ingot"	,EnumRarity.UNCOMMON,"ingotQuartzEnrichedIron"	,"",64),
	OPEN_0145					("open"							,EnumRarity.UNCOMMON,""							,"",64),
	OPEN_0146					("open"							,EnumRarity.UNCOMMON,""							,"",64),
	QUARTZ_ENRICHED_IRON_PLATE	("quartz_enriched_iron_plate"	,EnumRarity.UNCOMMON,"plateQuartzEnrichedIron"	,"",64),

	ARDITE_CRUSHED_ORE	("ardite_crushed_ore"	,EnumRarity.RARE,"crushedArdite",""			,64),
	ARDITE_DUST			("ardite_dust"			,EnumRarity.RARE,"dustArdite"	,""			,64),
	OPEN_0151			("open"					,EnumRarity.RARE,""				,""			,64),
	ARDITE_CRYSTAL		("ardite_crystal"		,EnumRarity.RARE,"crystalArdite",""			,64),
	ARDITE_SHARD		("ardite_shard"			,EnumRarity.RARE,"shardArdite"	,""			,64),
	ARDITE_NUGGET		("ardite_nugget"		,EnumRarity.RARE,"nuggetArdite"	,""			,64),
	ARDITE_CLUMP		("ardite_clump"			,EnumRarity.RARE,"clumpArdite"	,""			,64),
	ARDITE_INGOT		("ardite_ingot"			,EnumRarity.RARE,"ingotArdite"	,""			,64),
	ARDITE_ROD			("ardite_rod"			,EnumRarity.RARE,"stickArdite"	,"rodArdite",64),
	ARDITE_GEAR			("ardite_gear"			,EnumRarity.RARE,"gearArdite"	,""			,64),
	ARDITE_PLATE		("ardite_plate"			,EnumRarity.RARE,"plateArdite"	,""			,64),

	COBALT_CRUSHED_ORE	("cobalt_crushed_ore"	,EnumRarity.RARE,"crushedCobalt",""			,64),
	COBALT_DUST			("cobalt_dust"			,EnumRarity.RARE,"dustCobalt"	,""			,64),
	OPEN_0161			("open"					,EnumRarity.RARE,""				,""			,64),
	COBALT_CRYSTAL		("cobalt_crystal"		,EnumRarity.RARE,"crystalCobalt",""			,64),
	COBALT_SHARD		("cobalt_shard"			,EnumRarity.RARE,"shardCobalt"	,""			,64),
	COBALT_NUGGET		("cobalt_nugget"		,EnumRarity.RARE,"nuggetCobalt"	,""			,64),
	COBALT_CLUMP		("cobalt_clump"			,EnumRarity.RARE,"clumpCobalt"	,""			,64),
	COBALT_INGOT		("cobalt_ingot"			,EnumRarity.RARE,"ingotCobalt"	,""			,64),
	COBALT_ROD			("cobalt_rod"			,EnumRarity.RARE,"stickCobalt"	,"rodCobalt",64),
	COBALT_GEAR			("cobalt_gear"			,EnumRarity.RARE,"gearCobalt"	,""			,64),
	COBALT_PLATE		("cobalt_plate"			,EnumRarity.RARE,"plateCobalt"	,""			,64),

	IRIDIUM_CRUSHED_ORE	("iridium_crushed_ore"	,EnumRarity.EPIC,"crushedIridium"	,""				,64),
	IRIDIUM_DUST		("iridium_dust"			,EnumRarity.EPIC,"dustIridium"		,""				,64),
	OPEN_0171			("open"					,EnumRarity.EPIC,""					,""				,64),
	IRIDIUM_CRYSTAL		("iridium_crystal"		,EnumRarity.EPIC,"crystalIridium"	,""				,64),
	IRIDIUM_SHARD		("iridium_shard"		,EnumRarity.EPIC,"shardIridium"		,""				,64),
	IRIDIUM_NUGGET		("iridium_nugget"		,EnumRarity.EPIC,"nuggetIridium"	,""				,64),
	IRIDIUM_CLUMP		("iridium_clump"		,EnumRarity.EPIC,"clumpIridium"		,""				,64),
	IRIDIUM_INGOT		("iridium_ingot"		,EnumRarity.EPIC,"ingotIridium"		,""				,64),
	IRIDIUM_ROD			("iridium_rod"			,EnumRarity.EPIC,"stickIridium"		,"rodIridium"	,64),
	IRIDIUM_GEAR		("iridium_gear"			,EnumRarity.EPIC,"gearIridium"		,""				,64),
	IRIDIUM_PLATE		("iridium_plate"		,EnumRarity.EPIC,"plateIridium"		,""				,64),

	DRACONIUM_CRUSHED_ORE	("draconium_crushed_ore",EnumRarity.EPIC,"crushedDraconium"	,""				,64),
	DRACONIUM_DUST			("draconium_dust"		,EnumRarity.EPIC,"dustDraconium"	,""				,64),
	OPEN_0181				("open"					,EnumRarity.EPIC,""					,""				,64),
	DRACONIUM_CRYSTAL		("draconium_crystal"	,EnumRarity.EPIC,"crystalDraconium"	,""				,64),
	DRACONIUM_SHARD			("draconium_shard"		,EnumRarity.EPIC,"shardDraconium"	,""				,64),
	DRACONIUM_NUGGET		("draconium_nugget"		,EnumRarity.EPIC,"nuggetDraconium"	,""				,64),
	DRACONIUM_CLUMP			("draconium_clump"		,EnumRarity.EPIC,"clumpDraconium"	,""				,64),
	DRACONIUM_INGOT			("draconium_ingot"		,EnumRarity.EPIC,"ingotDraconium"	,""				,64),
	DRACONIUM_ROD			("draconium_rod"		,EnumRarity.EPIC,"stickDraconium"	,"rodDraconium"	,64),
	DRACONIUM_GEAR			("draconium_gear"		,EnumRarity.EPIC,"gearDraconium"	,""				,64),
	DRACONIUM_PLATE			("draconium_plate"		,EnumRarity.EPIC,"plateDraconium"	,""				,64),

	OPEN_0190					("open"						,EnumRarity.EPIC,""							,""						,64),
	AWAKENED_DRACONIUM_DUST		("awakened_draconium_dust"	,EnumRarity.EPIC,"dustDraconiumAwakened"	,""						,64),
	OPEN_0191					("open"						,EnumRarity.EPIC,""							,""						,64),
	OPEN_0192					("open"						,EnumRarity.EPIC,""							,""						,64),
	OPEN_0193					("open"						,EnumRarity.EPIC,""							,""						,64),
	AWAKENED_DRACONIUM_NUGGET	("awakened_draconium_nugget",EnumRarity.EPIC,"nuggetDraconiumAwakened"	,""						,64),
	AWAKENED_DRACONIUM_CLUMP	("awakened_draconium_clump"	,EnumRarity.EPIC,"clumpDraconiumAwakened"	,""						,64),
	AWAKENED_DRACONIUM_INGOT	("awakened_draconium_ingot"	,EnumRarity.EPIC,"ingotDraconiumAwakened"	,""						,64),
	AWAKENED_DRACONIUM_ROD		("awakened_draconium_rod"	,EnumRarity.EPIC,"stickDraconiumAwakened"	,"rodDraconiumAwakened"	,64),
	AWAKENED_DRACONIUM_GEAR		("awakened_draconium_gear"	,EnumRarity.EPIC,"gearDraconiumAwakened"	,""						,64),
	AWAKENED_DRACONIUM_PLATE	("awakened_draconium_plate"	,EnumRarity.EPIC,"plateDraconiumAwakened"	,""						,64),

	OPEN_0200				("open"						,EnumRarity.EPIC,""						,"",64),
	OPEN_0201				("open"						,EnumRarity.EPIC,""						,"",64),
	OPEN_0202				("open"						,EnumRarity.EPIC,""						,"",64),
	OPEN_0203				("open"						,EnumRarity.EPIC,""						,"",64),
	OPEN_0204				("open"						,EnumRarity.EPIC,""						,"",64),
	ELECTRICAL_STEEL_NUGGET	("electrical_steel_nugget"	,EnumRarity.EPIC,"nuggetElectricalSteel","",64),
	ELECTRICAL_STEEL_CLUMP	("electrical_steel_clump"	,EnumRarity.EPIC,"clumpElectricalSteel"	,"",64),
	ELECTRICAL_STEEL_INGOT	("electrical_steel_ingot"	,EnumRarity.EPIC,"ingotElectricalSteel"	,"",64),
	OPEN_0205				("open"						,EnumRarity.EPIC,""						,"",64),
	OPEN_0206				("open"						,EnumRarity.EPIC,""						,"",64),
	ELECTRICAL_STEEL_PLATE	("electrical_steel_plate"	,EnumRarity.EPIC,"plateElectricalSteel"	,"",64),

	OPEN_0210				("open"						,EnumRarity.EPIC,""						,"",64),
	OPEN_0211				("open"						,EnumRarity.EPIC,""						,"",64),
	OPEN_0212				("open"						,EnumRarity.EPIC,""						,"",64),
	OPEN_0213				("open"						,EnumRarity.EPIC,""						,"",64),
	OPEN_0214				("open"						,EnumRarity.EPIC,""						,"",64),
	ENERGETIC_ALLOY_NUGGET	("energetic_alloy_nugget"	,EnumRarity.EPIC,"nuggetEnergeticAlloy"	,"",64),
	ENERGETIC_ALLOY_CLUMP	("energetic_alloy_clump"	,EnumRarity.EPIC,"clumpEnergeticAlloy"	,"",64),
	ENERGETIC_ALLOY_INGOT	("energetic_alloy_ingot"	,EnumRarity.EPIC,"ingotEnergeticAlloy"	,"",64),
	OPEN_0215				("open"						,EnumRarity.EPIC,""						,"",64),
	OPEN_0216				("open"						,EnumRarity.EPIC,""						,"",64),
	ENERGETIC_ALLOY_PLATE	("energetic_alloy_plate"	,EnumRarity.EPIC,"plateEnergeticAlloy"	,"",64),

	OPEN_0220			("open"					,EnumRarity.EPIC,""						,"",64),
	OPEN_0221			("open"					,EnumRarity.EPIC,""						,"",64),
	OPEN_0222			("open"					,EnumRarity.EPIC,""						,"",64),
	OPEN_0223			("open"					,EnumRarity.EPIC,""						,"",64),
	OPEN_0224			("open"					,EnumRarity.EPIC,""						,"",64),
	VIBRANT_ALLOY_NUGGET("vibrant_alloy_nugget"	,EnumRarity.EPIC,"nuggetVibrantAlloy"	,"",64),
	VIBRANT_ALLOY_CLUMP	("vibrant_alloy_clump"	,EnumRarity.EPIC,"clumpVibrantAlloy"	,"",64),
	VIBRANT_ALLOY_INGOT	("vibrant_alloy_ingot"	,EnumRarity.EPIC,"ingotVibrantAlloy"	,"",64),
	OPEN_0225			("open"					,EnumRarity.EPIC,""						,"",64),
	OPEN_0226			("open"					,EnumRarity.EPIC,""						,"",64),
	VIBRANT_ALLOY_PLATE	("vibrant_alloy_plate"	,EnumRarity.EPIC,"plateVibrantAlloy"	,"",64),

	OPEN_0230				("open"					,EnumRarity.EPIC,""						,"",64),
	OPEN_0231				("open"					,EnumRarity.EPIC,""						,"",64),
	OPEN_0232				("open"					,EnumRarity.EPIC,""						,"",64),
	OPEN_0233				("open"					,EnumRarity.EPIC,""						,"",64),
	OPEN_0234				("open"					,EnumRarity.EPIC,""						,"",64),
	REDSTONE_ALLOY_NUGGET	("redstone_alloy_nugget",EnumRarity.EPIC,"nuggetRedstoneAlloy"	,"",64),
	REDSTONE_ALLOY_CLUMP	("redstone_alloy_clump"	,EnumRarity.EPIC,"clumpRedstoneAlloy"	,"",64),
	REDSTONE_ALLOY_INGOT	("redstone_alloy_ingot"	,EnumRarity.EPIC,"ingotRedstoneAlloy"	,"",64),
	OPEN_0235				("open"					,EnumRarity.EPIC,""						,"",64),
	OPEN_0236				("open"					,EnumRarity.EPIC,""						,"",64),
	REDSTONE_ALLOY_PLATE	("redstone_alloy_plate"	,EnumRarity.EPIC,"plateRedstoneAlloy"	,"",64),

	OPEN_0240				("open"						,EnumRarity.EPIC,""						,"",64),
	OPEN_0241				("open"						,EnumRarity.EPIC,""						,"",64),
	OPEN_0242				("open"						,EnumRarity.EPIC,""						,"",64),
	OPEN_0243				("open"						,EnumRarity.EPIC,""						,"",64),
	OPEN_0244				("open"						,EnumRarity.EPIC,""						,"",64),
	CONDUCTIVE_IRON_NUGGET	("conductive_iron_nugget"	,EnumRarity.EPIC,"nuggetConductiveIron"	,"",64),
	CONDUCTIVE_IRON_CLUMP	("conductive_iron_clump"	,EnumRarity.EPIC,"clumpConductiveIron"	,"",64),
	CONDUCTIVE_IRON_INGOT	("conductive_iron_ingot"	,EnumRarity.EPIC,"ingotConductiveIron"	,"",64),
	OPEN_0245				("open"						,EnumRarity.EPIC,""						,"",64),
	OPEN_0246				("open"						,EnumRarity.EPIC,""						,"",64),
	CONDUCTIVE_IRON_PLATE	("conductive_iron_plate"	,EnumRarity.EPIC,"plateConductiveIron"	,"",64),

	OPEN_0250				("open"					,EnumRarity.EPIC,""						,"",64),
	OPEN_0251				("open"					,EnumRarity.EPIC,""						,"",64),
	OPEN_0252				("open"					,EnumRarity.EPIC,""						,"",64),
	OPEN_0253				("open"					,EnumRarity.EPIC,""						,"",64),
	OPEN_0254				("open"					,EnumRarity.EPIC,""						,"",64),
	PULSATING_IRON_NUGGET	("pulsating_iron_nugget",EnumRarity.EPIC,"nuggetPulsatingIron"	,"",64),
	PULSATING_IRON_CLUMP	("pulsating_iron_clump"	,EnumRarity.EPIC,"clumpPulsatingIron"	,"",64),
	PULSATING_IRON_INGOT	("pulsating_iron_ingot"	,EnumRarity.EPIC,"ingotPulsatingIron"	,"",64),
	OPEN_0255				("open"					,EnumRarity.EPIC,""						,"",64),
	OPEN_0256				("open"					,EnumRarity.EPIC,""						,"",64),
	PULSATING_IRON_PLATE	("pulsating_iron_plate"	,EnumRarity.EPIC,"platePulsatingIron"	,"",64),

	OPEN_0260			("open"				,EnumRarity.EPIC,""					,"",64),
	OPEN_0261			("open"				,EnumRarity.EPIC,""					,"",64),
	OPEN_0262			("open"				,EnumRarity.EPIC,""					,"",64),
	OPEN_0263			("open"				,EnumRarity.EPIC,""					,"",64),
	OPEN_0264			("open"				,EnumRarity.EPIC,""					,"",64),
	DARK_STEEL_NUGGET	("dark_steel_nugget",EnumRarity.EPIC,"nuggetDarkSteel"	,"",64),
	DARK_STEEL_CLUMP	("dark_steel_clump"	,EnumRarity.EPIC,"clumpDarkSteel"	,"",64),
	DARK_STEEL_INGOT	("dark_steel_ingot"	,EnumRarity.EPIC,"ingotDarkSteel"	,"",64),
	OPEN_0265			("open"				,EnumRarity.EPIC,""					,"",64),
	OPEN_0266			("open"				,EnumRarity.EPIC,""					,"",64),
	DARK_STEEL_PLATE	("dark_steel_plate"	,EnumRarity.EPIC,"plateDarkSteel"	,"",64),

	OPEN_0270		("open"				,EnumRarity.EPIC,""					,"",64),
	OPEN_0271		("open"				,EnumRarity.EPIC,""					,"",64),
	OPEN_0272		("open"				,EnumRarity.EPIC,""					,"",64),
	OPEN_0273		("open"				,EnumRarity.EPIC,""					,"",64),
	OPEN_0274		("open"				,EnumRarity.EPIC,""					,"",64),
	SOULARIUM_NUGGET("soularium_nugget"	,EnumRarity.EPIC,"nuggetSoularium"	,"",64),
	SOULARIUM_CLUMP	("soularium_clump"	,EnumRarity.EPIC,"clumpSoularium"	,"",64),
	SOULARIUM_INGOT	("soularium_ingot"	,EnumRarity.EPIC,"ingotSoularium"	,"",64),
	OPEN_0275		("open"				,EnumRarity.EPIC,""					,"",64),
	OPEN_0276		("open"				,EnumRarity.EPIC,""					,"",64),
	SOULARIUM_PLATE	("soularium_plate"	,EnumRarity.EPIC,"plateSoularium"	,"",64),

	OPEN_0280		("open"				,EnumRarity.EPIC,""					,"",64),
	OPEN_0281		("open"				,EnumRarity.EPIC,""					,"",64),
	OPEN_0282		("open"				,EnumRarity.EPIC,""					,"",64),
	OPEN_0283		("open"				,EnumRarity.EPIC,""					,"",64),
	OPEN_0284		("open"				,EnumRarity.EPIC,""					,"",64),
	END_STEEL_NUGGET("end_steel_nugget"	,EnumRarity.EPIC,"nuggetEndSteel"	,"",64),
	END_STEEL_CLUMP	("end_steel_clump"	,EnumRarity.EPIC,"clumpEndSteel"	,"",64),
	END_STEEL_INGOT	("end_steel_ingot"	,EnumRarity.EPIC,"ingotEndSteel"	,"",64),
	OPEN_0285		("open"				,EnumRarity.EPIC,""					,"",64),
	OPEN_0286		("open"				,EnumRarity.EPIC,""					,"",64),
	END_STEEL_PLATE	("end_steel_plate"	,EnumRarity.EPIC,"plateEndSteel"	,"",64),

	OPEN_0290				("open"						,EnumRarity.UNCOMMON,""						,"",64),
	REFINED_OBSIDIAN_DUST	("refined_obsidian_dust"	,EnumRarity.UNCOMMON,"dustRefinedObsidian"	,"",64),
	OPEN_0291				("open"						,EnumRarity.UNCOMMON,""						,"",64),
	OPEN_0292				("open"						,EnumRarity.UNCOMMON,""						,"",64),
	OPEN_0293				("open"						,EnumRarity.UNCOMMON,""						,"",64),
	REFINED_OBSIDIAN_NUGGET	("refined_obsidian_nugget"	,EnumRarity.UNCOMMON,"nuggetRefinedObsidian","",64),
	REFINED_OBSIDIAN_CLUMP	("refined_obsidian_clump"	,EnumRarity.UNCOMMON,"clumpRefinedObsidian"	,"",64),
	REFINED_OBSIDIAN_INGOT	("refined_obsidian_ingot"	,EnumRarity.UNCOMMON,"ingotRefinedObsidian"	,"",64),
	OPEN_0294				("open"						,EnumRarity.UNCOMMON,""						,"",64),
	OPEN_0295				("open"						,EnumRarity.UNCOMMON,""						,"",64),
	REFINED_OBSIDIAN_PLATE	("refined_obsidian_plate"	,EnumRarity.UNCOMMON,"plateRefinedObsidian"	,"",64),

	OPEN_0300				("open"						,EnumRarity.RARE,""							,"",64),
	REFINED_GLOWSTONE_DUST	("refined_glowstone_dust"	,EnumRarity.RARE,"dustRefinedGlowstone"		,"",64),
	OPEN_0301				("open"						,EnumRarity.RARE,""							,"",64),
	OPEN_0302				("open"						,EnumRarity.RARE,""							,"",64),
	OPEN_0303				("open"						,EnumRarity.RARE,""							,"",64),
	REFINED_GLOWSTONE_NUGGET("refined_glowstone_nugget"	,EnumRarity.RARE,"nuggetRefinedGlowstone"	,"",64),
	REFINED_GLOWSTONE_CLUMP	("refined_glowstone_clump"	,EnumRarity.RARE,"clumpRefinedGlowstone"	,"",64),
	REFINED_GLOWSTONE_INGOT	("refined_glowstone_ingot"	,EnumRarity.RARE,"ingotRefinedGlowstone"	,"",64),
	OPEN_0304				("open"						,EnumRarity.RARE,""							,"",64),
	OPEN_0305				("open"						,EnumRarity.RARE,""							,"",64),
	REFINED_GLOWSTONE_PLATE	("refined_glowstone_plate"	,EnumRarity.RARE,"plateRefinedGlowstone"	,"",64),

	OPEN_0310		("open"			,EnumRarity.UNCOMMON,""				,"",64),
	OPEN_0311		("open"			,EnumRarity.UNCOMMON,""				,"",64),
	OPEN_0312		("open"			,EnumRarity.UNCOMMON,""				,"",64),
	OPEN_0313		("open"			,EnumRarity.UNCOMMON,""				,"",64),
	OPEN_0314		("open"			,EnumRarity.UNCOMMON,""				,"",64),
	OPEN_0315		("open"			,EnumRarity.UNCOMMON,""				,"",64),
	OPEN_0316		("open"			,EnumRarity.UNCOMMON,""				,"",64),
	SPECTRE_INGOT	("spectre_ingot",EnumRarity.UNCOMMON,"ingotSpectre"	,"",64),
	OPEN_0317		("open"			,EnumRarity.UNCOMMON,""				,"",64),
	OPEN_0318		("open"			,EnumRarity.UNCOMMON,""				,"",64),
	SPECTRE_PLATE	("spectre_plate",EnumRarity.UNCOMMON,"plateSpectre"	,"",64),

	OPEN_1100("open",EnumRarity.COMMON,"","",64),
	OPEN_1101("open",EnumRarity.COMMON,"","",64),
	OPEN_1102("open",EnumRarity.COMMON,"","",64),
	OPEN_1103("open",EnumRarity.COMMON,"","",64),
	OPEN_1104("open",EnumRarity.COMMON,"","",64),
	OPEN_1105("open",EnumRarity.COMMON,"","",64),
	OPEN_1106("open",EnumRarity.COMMON,"","",64),
	OPEN_1107("open",EnumRarity.COMMON,"","",64),
	OPEN_1108("open",EnumRarity.COMMON,"","",64),
	OPEN_1109("open",EnumRarity.COMMON,"","",64),
	OPEN_1110("open",EnumRarity.COMMON,"","",64),

	OPEN_1220("open",EnumRarity.COMMON,"","",64),
	OPEN_1221("open",EnumRarity.COMMON,"","",64),
	OPEN_1222("open",EnumRarity.COMMON,"","",64),
	OPEN_1223("open",EnumRarity.COMMON,"","",64),
	OPEN_1224("open",EnumRarity.COMMON,"","",64),
	OPEN_1225("open",EnumRarity.COMMON,"","",64),
	OPEN_1226("open",EnumRarity.COMMON,"","",64),
	OPEN_1227("open",EnumRarity.COMMON,"","",64),
	OPEN_1228("open",EnumRarity.COMMON,"","",64),
	OPEN_1229("open",EnumRarity.COMMON,"","",64),
	OPEN_1230("open",EnumRarity.COMMON,"","",64),

	OPEN_0330		("open"				,EnumRarity.COMMON,""				,"",64),
	OPEN_0331		("open"				,EnumRarity.COMMON,""				,"",64),
	OPEN_0332		("open"				,EnumRarity.COMMON,""				,"",64),
	OPEN_0333		("open"				,EnumRarity.COMMON,""				,"",64),
	OPEN_0334		("open"				,EnumRarity.COMMON,""				,"",64),
	PIG_IRON_NUGGET	("pig_iron_nugget"	,EnumRarity.COMMON,"nuggetPigiron"	,"",64),
	PIG_IRON_CLUMP	("pig_iron_clump"	,EnumRarity.COMMON,"clumpPigiron"	,"",64),
	PIG_IRON_INGOT	("pig_iron_ingot"	,EnumRarity.COMMON,"ingotPigiron"	,"",64),
	OPEN_0335		("open"				,EnumRarity.COMMON,""				,"",64),
	OPEN_0336		("open"				,EnumRarity.COMMON,""				,"",64),
	OPEN_0337		("open"				,EnumRarity.COMMON,""				,"",64),

	OPEN_0340			("open"					,EnumRarity.COMMON,""					,"",64),
	OPEN_0341			("open"					,EnumRarity.COMMON,""					,"",64),
	OPEN_0342			("open"					,EnumRarity.COMMON,""					,"",64),
	OPEN_0343			("open"					,EnumRarity.COMMON,""					,"",64),
	OPEN_0344			("open"					,EnumRarity.COMMON,""					,"",64),
	KNIGHT_SLIME_NUGGET	("knight_slime_nugget"	,EnumRarity.COMMON,"nuggetKnightslime"	,"",64),
	KNIGHT_SLIME_CLUMP	("knight_slime_clump"	,EnumRarity.COMMON,"clumpKnightslime"	,"",64),
	KNIGHT_SLIME_INGOT	("knight_slime_ingot"	,EnumRarity.COMMON,"ingotKnightslime"	,"",64),
	OPEN_0345			("open"					,EnumRarity.COMMON,""					,"",64),
	OPEN_0346			("open"					,EnumRarity.COMMON,""					,"",64),
	OPEN_0347			("open"					,EnumRarity.COMMON,""					,"",64),

	OPEN_0350		("open"				,EnumRarity.RARE,""					,"",64),
	OPEN_0351		("open"				,EnumRarity.RARE,""					,"",64),
	OPEN_0352		("open"				,EnumRarity.RARE,""					,"",64),
	OPEN_0353		("open"				,EnumRarity.RARE,""					,"",64),
	OPEN_0354		("open"				,EnumRarity.RARE,""					,"",64),
	MANYULLYN_NUGGET("manyullyn_nugget"	,EnumRarity.RARE,"nuggetManyullyn"	,"",64),
	MANYULLYN_CLUMP	("manyullyn_clump"	,EnumRarity.RARE,"clumpManyullyn"	,"",64),
	MANYULLYN_INGOT	("manyullyn_ingot"	,EnumRarity.RARE,"ingotManyullyn"	,"",64),
	OPEN_0355		("open"				,EnumRarity.RARE,""					,"",64),
	OPEN_0356		("open"				,EnumRarity.RARE,""					,"",64),
	OPEN_0357		("open"				,EnumRarity.RARE,""					,"",64),

	OPEN_0360		("open"				,EnumRarity.RARE,""					,"",64),
	SIGNALUM_DUST	("signalum_dust"	,EnumRarity.RARE,"dustSignalum"		,"",64),
	OPEN_0361		("open"				,EnumRarity.RARE,""					,"",64),
	OPEN_0362		("open"				,EnumRarity.RARE,""					,"",64),
	OPEN_0363		("open"				,EnumRarity.RARE,""					,"",64),
	SIGNALUM_NUGGET	("signalum_nugget"	,EnumRarity.RARE,"nuggetSignalum"	,"",64),
	SIGNALUM_CLUMP	("signalum_clump"	,EnumRarity.RARE,"clumpSignalum"	,"",64),
	SIGNALUM_INGOT	("signalum_ingot"	,EnumRarity.RARE,"ingotSignalum"	,"",64),
	OPEN_0364		("open"				,EnumRarity.RARE,""					,"",64),
	SIGNALUM_GEAR	("signalum_gear"	,EnumRarity.RARE,"gearSignalum"		,"",64),
	SIGNALUM_PLATE	("signalum_plate"	,EnumRarity.RARE,"plateSignalum"	,"",64),

	OPEN_0370		("open"				,EnumRarity.EPIC,""					,"",64),
	ENDERIUM_DUST	("enderium_dust"	,EnumRarity.EPIC,"dustEnderium"		,"",64),
	OPEN_0371		("open"				,EnumRarity.EPIC,""					,"",64),
	OPEN_0372		("open"				,EnumRarity.EPIC,""					,"",64),
	OPEN_0373		("open"				,EnumRarity.EPIC,""					,"",64),
	ENDERIUM_NUGGET	("enderium_nugget"	,EnumRarity.EPIC,"nuggetEnderium"	,"",64),
	ENDERIUM_CLUMP	("enderium_clump"	,EnumRarity.EPIC,"clumpEnderium"	,"",64),
	ENDERIUM_INGOT	("enderium_ingot"	,EnumRarity.EPIC,"ingotEnderium"	,"",64),
	OPEN_0374		("open"				,EnumRarity.EPIC,""					,"",64),
	ENDERIUM_GEAR	("enderium_gear"	,EnumRarity.EPIC,"gearEnderium"		,"",64),
	ENDERIUM_PLATE	("enderium_plate"	,EnumRarity.EPIC,"plateEnderium"	,"",64),

	OPEN_0380		("open"			,EnumRarity.RARE,""				,"",64),
	LUMIUM_DUST		("lumium_dust"	,EnumRarity.RARE,"dustLumium"	,"",64),
	OPEN_0381		("open"			,EnumRarity.RARE,""				,"",64),
	OPEN_0382		("open"			,EnumRarity.RARE,""				,"",64),
	OPEN_0383		("open"			,EnumRarity.RARE,""				,"",64),
	LUMIUM_NUGGET	("lumium_nugget",EnumRarity.RARE,"nuggetLumium"	,"",64),
	LUMIUM_CLUMP	("lumium_clump"	,EnumRarity.RARE,"clumpLumium"	,"",64),
	LUMIUM_INGOT	("lumium_ingot"	,EnumRarity.RARE,"ingotLumium"	,"",64),
	OPEN_0384		("open"			,EnumRarity.RARE,""				,"",64),
	LUMIUM_GEAR		("lumium_gear"	,EnumRarity.RARE,"gearLumium"	,"",64),
	LUMIUM_PLATE	("lumium_plate"	,EnumRarity.RARE,"plateLumium"	,"",64),

	OPEN_0390				("open"					,EnumRarity.UNCOMMON,""					,"",64),
	OPEN_0391				("open"					,EnumRarity.UNCOMMON,""					,"",64),
	OPEN_0392				("open"					,EnumRarity.UNCOMMON,""					,"",64),
	OPEN_0393				("open"					,EnumRarity.UNCOMMON,""					,"",64),
	OPEN_0394				("open"					,EnumRarity.UNCOMMON,""					,"",64),
	ALUMINUM_BRASS_NUGGET	("aluminum_brass_nugget",EnumRarity.UNCOMMON,"nuggetAlubrass"	,"",64),
	ALUMINUM_BRASS_CLUMP	("aluminum_brass_clump"	,EnumRarity.UNCOMMON,"clumpAlubrass"	,"",64),
	ALUMINUM_BRASS_INGOT	("aluminum_brass_ingot"	,EnumRarity.UNCOMMON,"ingotAlubrass"	,"",64),
	OPEN_0395				("open"					,EnumRarity.UNCOMMON,""					,"",64),
	OPEN_0396				("open"					,EnumRarity.UNCOMMON,""					,"",64),
	OPEN_0397				("open"					,EnumRarity.UNCOMMON,""					,"",64),

	OPEN_0400	("open"			,EnumRarity.COMMON,""			,"",64),
	OPEN_0401	("open"			,EnumRarity.COMMON,""			,"",64),
	OPEN_0402	("open"			,EnumRarity.COMMON,""			,"",64),
	OPEN_0403	("open"			,EnumRarity.COMMON,""			,"",64),
	OPEN_0404	("open"			,EnumRarity.COMMON,""			,"",64),
	OPEN_0405	("open"			,EnumRarity.COMMON,""			,"",64),
	OPEN_0406	("open"			,EnumRarity.COMMON,""			,"",64),
	OPEN_0407	("open"			,EnumRarity.COMMON,""			,"",64),
	OPEN_0408	("open"			,EnumRarity.COMMON,""			,"",64),
	WOOD_GEAR	("wood_gear"	,EnumRarity.COMMON,"gearWood"	,"",64),
	WOOD_PLATE	("wood_plate"	,EnumRarity.COMMON,"plateWood"	,"",64),

	OPEN_0410	("open"			,EnumRarity.COMMON,""			,"",64),
	OPEN_0411	("open"			,EnumRarity.COMMON,""			,"",64),
	OPEN_0412	("open"			,EnumRarity.COMMON,""			,"",64),
	OPEN_0413	("open"			,EnumRarity.COMMON,""			,"",64),
	OPEN_0414	("open"			,EnumRarity.COMMON,""			,"",64),
	OPEN_0415	("open"			,EnumRarity.COMMON,""			,"",64),
	OPEN_0416	("open"			,EnumRarity.COMMON,""			,"",64),
	OPEN_0417	("open"			,EnumRarity.COMMON,""			,"",64),
	OPEN_0418	("open"			,EnumRarity.COMMON,""			,"",64),
	STONE_GEAR	("stone_gear"	,EnumRarity.COMMON,"gearStone"	,"",64),
	STONE_PLATE	("stone_plate"	,EnumRarity.COMMON,"plateStone"	,"",64),

	OPEN_0420		("open"				,EnumRarity.UNCOMMON,""				,""						,64),
	DIAMOND_DUST	("diamond_dust"		,EnumRarity.UNCOMMON,"dustDiamond"	,""						,64),
	OPEN_0421		("open"				,EnumRarity.UNCOMMON,""				,""						,64),
	OPEN_0422		("open"				,EnumRarity.UNCOMMON,""				,""						,64),
	OPEN_0423		("open"				,EnumRarity.UNCOMMON,""				,""						,64),
	DIAMOND_NUGGET	("diamond_nugget"	,EnumRarity.UNCOMMON,"nuggetDiamond",""						,64),
	OPEN_0424		("open"				,EnumRarity.UNCOMMON,""				,""						,64),
	OPEN_0425		("open"				,EnumRarity.UNCOMMON,""				,""						,64),
	OPEN_0426		("open"				,EnumRarity.UNCOMMON,""				,""						,64),
	DIAMOND_GEAR	("diamond_gear"		,EnumRarity.UNCOMMON,"gearDiamond"	,""						,64),
	DIAMOND_PLATE	("diamond_plate"	,EnumRarity.UNCOMMON,"plateDiamond"	,"itemCompressedDiamond",64),

	OPEN_0430		("open"				,EnumRarity.RARE,""				,"",64),
	EMERALD_DUST	("emerald_dust"		,EnumRarity.RARE,"dustEmerald"	,"",64),
	OPEN_0431		("open"				,EnumRarity.RARE,""				,"",64),
	OPEN_0432		("open"				,EnumRarity.RARE,""				,"",64),
	OPEN_0433		("open"				,EnumRarity.RARE,""				,"",64),
	EMERALD_NUGGET	("emerald_nugget"	,EnumRarity.RARE,"nuggetEmerald","",64),
	OPEN_0434		("open"				,EnumRarity.RARE,""				,"",64),
	OPEN_0435		("open"				,EnumRarity.RARE,""				,"",64),
	OPEN_0436		("open"				,EnumRarity.RARE,""				,"",64),
	EMERALD_GEAR	("emerald_gear"		,EnumRarity.RARE,"gearEmerald"	,"",64),
	EMERALD_PLATE	("emerald_plate"	,EnumRarity.RARE,"plateEmerald"	,"",64),

	OPEN_0440		("open"				,EnumRarity.COMMON,""			,"",64),
	SULFUR_DUST		("sulfur_dust"		,EnumRarity.COMMON,"dustSulfur"	,"",64),
	OPEN_0441		("open"				,EnumRarity.COMMON,""			,"",64),
	OPEN_0442		("open"				,EnumRarity.COMMON,""			,"",64),
	OPEN_0443		("open"				,EnumRarity.COMMON,""			,"",64),
	OPEN_0444		("open"				,EnumRarity.COMMON,""			,"",64),
	OPEN_0445		("open"				,EnumRarity.COMMON,""			,"",64),
	OPEN_0446		("open"				,EnumRarity.COMMON,""			,"",64),
	OPEN_0447		("open"				,EnumRarity.COMMON,""			,"",64),
	OPEN_0448		("open"				,EnumRarity.COMMON,""			,"",64),
	OPEN_0449		("open"				,EnumRarity.COMMON,""			,"",64),

	OPEN_0450	("open"			,EnumRarity.COMMON,""			,"",64),
	COAL_DUST	("coal_dust"	,EnumRarity.COMMON,"dustCoal"	,"",64),
	OPEN_0451	("open"			,EnumRarity.COMMON,""			,"",64),
	OPEN_0452	("open"			,EnumRarity.COMMON,""			,"",64),
	OPEN_0453	("open"			,EnumRarity.COMMON,""			,"",64),
	COAL_NUGGET	("coal_nugget"	,EnumRarity.COMMON,"nuggetCoal"	,"",64),
	COAL_CLUMP	("coal_clump"	,EnumRarity.COMMON,"smallCoal"	,"",64),
	OPEN_0454	("open"			,EnumRarity.COMMON,""			,"",64),
	OPEN_0455	("open"			,EnumRarity.COMMON,""			,"",64),
	OPEN_0456	("open"			,EnumRarity.COMMON,""			,"",64),
	OPEN_0457	("open"			,EnumRarity.COMMON,""			,"",64),

	OPEN_0460		("open"				,EnumRarity.COMMON,""			,"",64),
	COAL_COKE_DUST	("coal_coke_dust"	,EnumRarity.COMMON,"dustCoke"	,"",64),
	OPEN_0461		("open"				,EnumRarity.COMMON,""			,"",64),
	OPEN_0462		("open"				,EnumRarity.COMMON,""			,"",64),
	OPEN_0463		("open"				,EnumRarity.COMMON,""			,"",64),
	COAL_COKE_NUGGET("coal_coke_nugget"	,EnumRarity.COMMON,"nuggetCoke"	,"",64),
	COAL_COKE_CLUMP	("coal_coke_clump"	,EnumRarity.COMMON,"smallCoke"	,"",64),
	COAL_COKE		("coal_coke"		,EnumRarity.COMMON,"fuelCoke"	,"",64),
	OPEN_0464		("open"				,EnumRarity.COMMON,""			,"",64),
	OPEN_0465		("open"				,EnumRarity.COMMON,""			,"",64),
	OPEN_0466		("open"				,EnumRarity.COMMON,""			,"",64),

	OPEN_0470		("open"				,EnumRarity.COMMON,""				,"",64),
	CHARCOAL_DUST	("charcoal_dust"	,EnumRarity.COMMON,"dustCharcoal"	,"",64),
	OPEN_0471		("open"				,EnumRarity.COMMON,""				,"",64),
	OPEN_0472		("open"				,EnumRarity.COMMON,""				,"",64),
	OPEN_0473		("open"				,EnumRarity.COMMON,""				,"",64),
	CHARCOAL_NUGGET	("charcoal_nugget"	,EnumRarity.COMMON,"nuggetCharcoal"	,"",64),
	CHARCOAL_CLUMP	("charcoal_clump"	,EnumRarity.COMMON,"smallCharcoal"	,"",64),
	OPEN_0474		("open"				,EnumRarity.COMMON,""				,"",64),
	OPEN_0475		("open"				,EnumRarity.COMMON,""				,"",64),
	OPEN_0476		("open"				,EnumRarity.COMMON,""				,"",64),
	OPEN_0477		("open"				,EnumRarity.COMMON,""				,"",64),

	OPEN_0480			("open"					,EnumRarity.UNCOMMON,"","",64),
	URANIUM_DUST		("uranium_dust"			,EnumRarity.UNCOMMON,"","",64),
	OPEN_0481			("open"					,EnumRarity.UNCOMMON,"","",64),
	URANIUM_PURE_DUST	("uranium_pure_dust"	,EnumRarity.UNCOMMON,"","",64),
	OPEN_0482			("open"					,EnumRarity.UNCOMMON,"","",64),
	URANIUM_U235_DUST	("uranium_u235_dust"	,EnumRarity.UNCOMMON,"","",64),
	OPEN_0483			("open"					,EnumRarity.UNCOMMON,"","",64),
	URANIUM_U238_DUST	("uranium_u238_dust"	,EnumRarity.UNCOMMON,"","",64),

	URANIUM_CRUSHED_ORE ("uranium_crushed_ore"	,EnumRarity.UNCOMMON,"crushedUranium"	,"",64),
	URANIUM_DIOXIDE_DUST("uranium_dioxide_dust"	,EnumRarity.UNCOMMON,"dustYellorium"	,"",64),
	OPEN_0485			("open"					,EnumRarity.UNCOMMON,""					,"",64),
	OPEN_0486			("open"					,EnumRarity.UNCOMMON,""					,"",64),
	OPEN_0487			("open"					,EnumRarity.UNCOMMON,""					,"",64),
	OPEN_0488			("open"					,EnumRarity.UNCOMMON,""					,"",64),
	OPEN_0489			("open"					,EnumRarity.UNCOMMON,""					,"",64),
	URANIUM_INGOT		("uranium_ingot"		,EnumRarity.UNCOMMON,"ingotYellorium"	,"",64),
	OPEN_0490			("open"					,EnumRarity.UNCOMMON,""					,"",64),
	OPEN_0491			("open"					,EnumRarity.UNCOMMON,""					,"",64),
	OPEN_0492			("open"					,EnumRarity.UNCOMMON,""					,"",64),

	OPEN_0500		("open"				,EnumRarity.COMMON,""				,""			,64),
	GRAPHITE_DUST	("graphite_dust"	,EnumRarity.COMMON,"dustGraphite"	,""			,64),
	GRAPHITE_PLATE	("graphite_plate"	,EnumRarity.COMMON,"plateGraphite"	,""			,64),
	OPEN_0502		("open"				,EnumRarity.COMMON,""				,""			,64),
	OPEN_0503		("open"				,EnumRarity.COMMON,""				,""			,64),
	OPEN_0504		("open"				,EnumRarity.COMMON,""				,""			,64),
	OPEN_0505		("open"				,EnumRarity.COMMON,""				,""			,64),
	OPEN_0506		("open"				,EnumRarity.COMMON,""				,""			,64),
	OPEN_0507		("open"				,EnumRarity.COMMON,""				,""			,64),
	OPEN_0508		("open"				,EnumRarity.COMMON,""				,""			,64),
	SLAG			("slag"				,EnumRarity.COMMON,"crystalSlag"	,"itemSlag"	,64),

	OPEN_0510	("open"		,EnumRarity.RARE,""					,"",64),
	OPEN_0511	("open"		,EnumRarity.RARE,""					,"",64),
	OPEN_0512	("open"		,EnumRarity.RARE,""					,"",64),
	OPEN_0513	("open"		,EnumRarity.RARE,""					,"",64),
	OPEN_0514	("open"		,EnumRarity.RARE,""					,"",64),
	OPEN_0515	("open"		,EnumRarity.RARE,""					,"",64),
	OPEN_0516	("open"		,EnumRarity.RARE,""					,"",64),
	BIOTITE		("biotite"	,EnumRarity.RARE,"gemEnderBiotite"	,"",64),
	OPEN_0517	("open"		,EnumRarity.RARE,""					,"",64),
	OPEN_0518	("open"		,EnumRarity.RARE,""					,"",64),
	OPEN_0519	("open"		,EnumRarity.RARE,""					,"",64),

	NETHER_KEY	("nether_key"	,EnumRarity.RARE,"","",1),
	END_KEY		("end_key"		,EnumRarity.EPIC,"","",1);

	private String name;
	private EnumRarity rarity;
	private String recipeOreDict1;
	private String recipeOreDict2;
	private int maxSize;

	EnumMaterials(String name,EnumRarity rarity,String recipeOreDict1,String recipeOreDict2,int maxSize) {
		this.name = name;
		this.rarity = rarity;
		this.recipeOreDict1 = recipeOreDict1;
		this.recipeOreDict2 = recipeOreDict2;
		this.maxSize = maxSize;
	}

	@Override
	public String getName() {
		return name;
	}

	public EnumRarity getRarity() {
		return rarity;
	}

	public String getRecipeOreDict1() {
		return recipeOreDict1;
	}

	public String getRecipeOreDict2() {
		return recipeOreDict2;
	}

	public int getMaxSize() {
		return maxSize;
	}

}